### ISSUE TITLE
Version 6.2.0 - System.InvalidOperationException: 'Mapper already initialized. You must call Initialize once per application domain/process.'

### ISSUE THREAD

**Issue by byrneciaran** [AutoMapper/AutoMapper#2405] opened 2017-11-15 19:20 UTC
I'm using AutoMapper with Xamarin Android. It's no longer working in 6.2 and I'm receiving the exception: 

`System.InvalidOperationException: 'Mapper already initialised. You must call initialised once per application domain/process.'`

I was doing my initialisation in the OnCreate method of my Activity, but if the app is backgrounded and then resumed, the method gets called again and the the exception occurs. I don't know where else I can call it, due to the way Android is architected. I tried experimenting with singletons with no joy. 

### Mapping configuration

```
  Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Field, FormField>();
                cfg.CreateMap<Item, FormFieldItem>();
                cfg.CreateMap<Metadata, FormMetadata>();
                cfg.CreateMap<FormField, Field>();
                cfg.CreateMap<FormFieldItem, Item>();
                cfg.CreateMap<FormMetadata, Metadata>();
            });
```

### Version: x.y.z

6.2.0

### Expected behavior

This worked in versions before 6.1.0

### Actual behavior

System.InvalidOperationException: 'Mapper already initialized. You must call Initialize once per application domain/process.'

**Comment by lbargaoanu** [comment] 2017-11-15 21:01
Duplicate of #2399. You might want to watch #2404, but it should be easy to fix without it.

**Closed by lbargaoanu** 2017-11-15 21:01 UTC
