### ISSUE TITLE
Ignore ForSourceMember maps property anyway

### ISSUE THREAD

**Issue by matthiaslischka** [AutoMapper/AutoMapper#2000] opened 2017-03-13 13:51 UTC
Hi,
I've just noticed a, at least to me, strange behavior when trying to ignore a property on source member. The property will get mapped anyway. I know that I can use the ForSourceMember ignore for mapping validation (AssertConfigurationIsValid) for when the property only exists on the source member, but I also expected the property to be ignored in the mapping - regardless of where, source or target member, I ignore it.

Maybe I understand the "Ignore" wrong but I and some others (according to google) would have expected the ignore to work in both ways.

Here a simple test for reproduction - second test fails:

```
public class Person
{
    public string FirstName { get; set; }
}
public class PersonDto
{
    public string FirstName { get; set; }
}

[TestMethod]
public void Map_WithIgnoredMemberFirstName_FirstNameNotMapped()
{
    //Arrange
    Mapper.Initialize(cfg =>
        cfg.CreateMap<Person, PersonDto>()
            .ForMember(dto => dto.FirstName, opt => opt.Ignore())
    );

    //Act
    var personDto = Mapper.Map<PersonDto>(new Person() {FirstName = "Tom"});

    //Assert
    Mapper.AssertConfigurationIsValid();
    Assert.IsNull(personDto.FirstName);
}

[TestMethod]
public void Map_WithIgnoredSourceMemberFirstName_FirstNameNotMapped()
{
    //Arrange
    Mapper.Initialize(cfg =>
        cfg.CreateMap<Person, PersonDto>()
            .ForSourceMember(person => person.FirstName, opt => opt.Ignore())
    );

    //Act
    var personDto = Mapper.Map<PersonDto>(new Person() {FirstName = "Tom"});

    //Assert
    Mapper.AssertConfigurationIsValid();
    Assert.IsNull(personDto.FirstName);
}
```

BR,
Matthias

**Comment by lbargaoanu** [comment] 2017-03-13 14:19
Duplicate of https://github.com/AutoMapper/AutoMapper/issues/1556.

**Closed by lbargaoanu** 2017-03-13 14:19 UTC
