### ISSUE TITLE
System.ValueTuple in .Net 4.7

### ISSUE THREAD

**Issue by rbmanian75** [AutoMapper/AutoMapper#2771] opened 2018-08-22 14:07 UTC
In .Net 4.7 System.ValueTuple is included. We dont need the dependency package System.ValueTuple.
Please release nuget package for .net 4.7

**Comment by lbargaoanu** [comment] 2018-08-22 14:09
Duplicate of #2750. Just put the binding redirect and everything works.

**Closed by lbargaoanu** 2018-08-22 14:09 UTC
