### ISSUE TITLE
Call to Map clears list property with ConstructUsing.

### ISSUE THREAD

**Issue by JoasE** [AutoMapper/AutoMapper#3470] opened 2020-07-20 13:29 UTC
### Source/destination types

```csharp
// Source
class Model1
{
    public List<int> Ints { get; set; }
}

// Dest
class Model2
{
    public Model2(List<int> ints)
    {
        Ints = ints;
    }

    public List<int> Ints { get; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Model1, Model2>().ConstructUsing(x => new Model2(x.Ints));
```

### Expected behavior

In 9.0.0 the `Model1` and `Model2` instances their 'Ints' property both had the value of a `List<int>` containing `1`,`2`,`3`.

### Actual behavior

In 10.0.0 the `Model1` and `Model2` instances their 'Ints' property are both EMPTY `List<int>`'s.

### Steps to reproduce

```csharp
var model1 = new Model1()
{
    Ints = new List<int> { 1, 2, 3 }
};
var model2 = mapper.Map<Model2>(model);
```

**Comment by lbargaoanu** [comment] 2020-07-20 13:35
Duplicate of #3468.

**Closed by lbargaoanu** 2020-07-20 13:35 UTC
Labels: Question
