### ISSUE TITLE
Mapping silently fails between two instances of the same type without a map

### ISSUE THREAD

**Issue by brainbolt** [AutoMapper/AutoMapper#3493] opened 2020-09-03 18:52 UTC
### Source/destination types

```csharp
public class Foo
{
    public int Bar { get; set; }
}
```

### Mapping configuration

```csharp
var mapper = new MapperConfiguration(c => c.AddProfile<EmptyProfile>()).CreateMapper();

public class EmptyProfile : Profile
{
    public EmptyProfile() { }
} 
```

### Expected behavior

Either an `AutoMapperMappingException` (due to the lack of map) or a successful mapping.

### Actual behavior

Silent failure to map between two instances of the same type when a map isn't defined.

### Steps to reproduce

```csharp
public class EmptyProfile : Profile
{
    public EmptyProfile() { }
} 

public class Foo
{
    public int Bar { get; set; }
}

[Test]
void Main()
{
    var mapper = new MapperConfiguration(c => c.AddProfile<EmptyProfile>()).CreateMapper();
    var foo = new Foo(){Bar = 1};
    var baz = new Foo();
    mapper.Map(foo, baz); // does not throw AutoMapperMappingException
    Assert.AreEqual(foo.Bar, baz.Bar); // fails
}
```
Adding `CreateMap<Foo, Foo>();` to `EmptyProfile` causes the test pass.

**Comment by lbargaoanu** [comment] 2020-09-04 05:03
Duplicate of #3480.

**Closed by lbargaoanu** 2020-09-04 05:03 UTC
Labels: Question
