### ISSUE TITLE
AfterMap()/BeforeMap() getting invoked multiple times

### ISSUE THREAD

**Issue by brittonbeckham** [AutoMapper/AutoMapper#1357] opened 2016-06-23 15:21 UTC
I'm currently on 4.1.1.

I have had this happen on two separate projects in two separate occasions. The first time I thought I was going nuts and just found a different way to do what I needed, but now it is happening once again and. I've have spend time looking through the Github release notes and have not seen and closed Issues that resolve `AfterMap()` problems, but I would like to ask here to see if this was a known issue for 4.1.1 or not. I can recreate this issue every time I use `AfterMap()` on any of my maps. My current work around is to put the `AfterMap()` logic in `ConstructUsing()`. This is happening with both `AfterMap ()` and `BeforeMap()`

Is this even a known issue?
Is this resolved in 4.2.0+ ?

**Comment by brittonbeckham** [comment] 2016-06-23 15:24
Here is my code for reference; `AfterMap()` is getting invoked 10 times on this Map:

```c#
Mapper.CreateMap<StorefrontDealCacheItem, LiveStorefrontDeal>()
	.ForMember(dest => dest.StorefrontDealStatus, opt => opt.ResolveUsing(src => StorefrontDealHelpers.CalculateStorefrontDealStatus(src.StartDate, src.EndDate)))
	.AfterMap((src, dest) => {

		var likeCountTask = _cahcedDealValueAgent.GetDealLikeCount(src.DealId);
		var soldQuantitiesTask = _cahcedDealValueAgent.GetDealSoldQuantity(src.DealId);
		var optionsTask = _cahcedDealValueAgent.GetOptionsAndVariantSoldQuantities(new[] { src.DealId });
		var sellerShipTimesTask = _cahcedDealValueAgent.GetSellerShipTime(src.SellerAccountId);

		//get all cached values async
		Task.WaitAll(soldQuantitiesTask, optionsTask, sellerShipTimesTask);

		var likeCount = likeCountTask.Result;
		var soldQuantity = soldQuantitiesTask.Result;
		var optionsCacheItem = optionsTask.Result.OptionsCacheItems.GetValueOrDefault(src.DealId);
		var sellerShipTimeDto = sellerShipTimesTask.Result;

		dest.LikeCount = likeCount;
		dest.IsLikelySellOut = StorefrontDealHelpers.IsLikelySellOut(src.Quantity, likeCount);
		dest.SoldQuantity = GetSoldQuantityWithAb(src, soldQuantity).Result;
		dest.RemainingQuantity = StorefrontDealHelpers.CalculateRemainingQuantity(src.Quantity, soldQuantity);
		dest.IsSoldOut = StorefrontDealHelpers.IsSoldOut(src.Quantity, soldQuantity);
		dest.AverageShipTime = src.IsPersonalized || src.IsHandmade || src.IsDeliveredElectronically ? null : sellerShipTimeDto?.AvgDaysToShipStandard;

		if (optionsCacheItem != null)
		{
			dest.Inventory = StorefrontDealInventoryHelper.BuildInventory(optionsCacheItem.Variants, optionsTask.Result.VariantSoldQuantities);
			dest.Options = optionsCacheItem.Options;
			dest.Variants = optionsCacheItem.Variants;
		}
	});
```

**Comment by jbogard** [comment] 2016-06-23 15:29
It's resolved in the 5.0 versions at least.

**Comment by brittonbeckham** [comment] 2016-06-23 17:29
So is/was this a known issue with 4.x?

**Comment by jbogard** [comment] 2016-06-23 21:18
Yep! https://github.com/AutoMapper/AutoMapper/issues/43 and we have an explicit test in there now.

And good god that AfterMap config looks complicated.

**Comment by brittonbeckham** [comment] 2016-06-23 21:41
So that issue (#43) is from 2011 -- was it fixed already once and now has come back for a second showing??

> And good god that AfterMap config looks complicated.

Yes, but AutoMapper hides away the ugly and shelters us from it's hideousness.

---
One additional question for `AfterMap`. When you use `AfterMap` on one type of configuration and then in another configuration use `.Include<>()` which includes the config that has `AfterMap`, will `AfterMap` from the included config be called?

Example: 
```c#
Mapper.CreateMap<StorefrontDealCacheItem, LiveStorefrontDeal>()
	.AfterMap( /*do something*/)

Mapper.CreateMap<StorefrontDealCacheItem, DealDetails>()
	.IncludeBase<StorefrontDealCacheItem, LiveStorefrontDeal>()

//will the following line trigger after map from the LiveStroefrontDeal config?
Mapper.Map<DealDetails>(sourceCache);
```

**Comment by jbogard** [comment] 2016-06-24 18:49
In 5.0, the AfterMap will be included with the inherited maps. And yeah, it looks like the issue was there and came back. But from what I see it's not in 5.0. Have you tried the myget build?

**Comment by Kostusev** [comment] 2016-07-20 09:17
In 5.0.2 AfterMap from section with Include called twice for me too. In 4.1.1 works correct.

**Comment by lbargaoanu** [comment] 2016-07-21 11:26
@Kostusev A repro would help. Make a gist that we can execute and see fail.

**Comment by lbargaoanu** [comment] 2016-07-21 11:44
CreateMap<BaseBaseSource, BaseBaseDest>().AfterMap((s, d)=>s.Dump()).Include<Source, Dest>().Include<BaseSource, BaseDest>();

This would call AfterMap three times, but this is by design I believe.

**Comment by Kostusev** [comment] 2016-07-21 11:49
private class A{}
private class A1 : A { }
private class A2 : A1 { }

private class B{public void AfterMap() => Console.WriteLine("AfterMap1");}
private class B1 : B{}
private class B2 : B1{}


            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<A, B>().Include<A1, B1>().AfterMap((a, b) => b.AfterMap());
                cfg.CreateMap<A1, B1>().Include<A2, B2>();
                cfg.CreateMap<A2, B2>();
            });
            Mapper.Map<B2>(new A2());

**Comment by lbargaoanu** [comment] 2016-07-21 12:01
A, B is included in A1, B1 which is included in A2, B2. I think that's expected behavior.

**Comment by Kostusev** [comment] 2016-07-21 12:03
I think it's a bug, because A mapped to B only once

**Comment by Kostusev** [comment] 2016-07-21 12:05
internal class Program
    {
        private static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<A, B>().Include<A1, B1>().AfterMap((a, b) => b.AfterMap());
                cfg.CreateMap<A1, B1>().Include<A2, B2>().AfterMap((a, b) => b.AfterMap1());
                cfg.CreateMap<A2, B2>().AfterMap((a, b) => b.AfterMap2());
            });
            Mapper.Map<B2>(new A2());
        }

        private class A{}
        private class A1 : A { }
        private class A2 : A1 { }

        private class B{public void AfterMap() => Console.WriteLine("AfterMap");}
        private class B1 : B { public void AfterMap1() => Console.WriteLine("AfterMap1"); }

**Comment by Kostusev** [comment] 2016-07-21 12:06
By your logic, what should be write here?

**Comment by SDzygun** [comment] 2016-07-21 15:34
I have 3 examples with different results
![1](https://cloud.githubusercontent.com/assets/6350853/17028863/a3c6b17c-4f71-11e6-9aab-6542cf613f79.png)
![2](https://cloud.githubusercontent.com/assets/6350853/17028866/a605e930-4f71-11e6-9fd5-49aee51f1883.png)
![3](https://cloud.githubusercontent.com/assets/6350853/17028867/a7721d66-4f71-11e6-925b-08dc32212b30.png)
Why the results is not equals??

**Comment by lbargaoanu** [comment] 2016-07-21 16:59
@jbogard Should we try to call it once even if it's included more than once?

**Comment by jbogard** [comment] 2016-07-21 19:31
Ah, do we recurse the Include? Is that's what's going on here? For each of these examples above, I would imagine the A2->B2 outputs would be the same.

**Comment by lbargaoanu** [comment] 2016-07-22 08:43
Yes, that's what happens and it surprises people.

**Comment by SDzygun** [comment] 2016-07-22 09:02
Outputs not the same.I have results:
1)     After2
        After1
        After
----------------------------------------
2)   After2
      After1
      After
      After
-------------------------------------
3)   After2
      After
      After1
      After

**Comment by lbargaoanu** [comment] 2016-07-22 13:13
Feel free to try the MyGet build :)

**Comment by lbargaoanu** [comment] 2016-07-25 09:15
This can be closed.

**Closed** 2016-07-25 12:10 UTC
Labels: Bug
