### ISSUE TITLE
Opt out of lazy expression compilation

### ISSUE THREAD

**Issue by sambauwens** [AutoMapper/AutoMapper#1693] opened 2016-09-21 09:40 UTC
As stated [in a blogpost comment](http://disq.us/p/1c1hg1u), I'm in the process of upgrading our WebAPI project to the latest version (5.1.1), and we get a big startup hit for multiple of our pages. AutoMapper takes 5-10s the first time it maps, but that's repeated for multiple pages. Is there a way to opt out of lazy compilation in production and compile everything at startup?

**Comment by lbargaoanu** [comment] 2016-09-21 10:25
Did you profile it?

**Comment by sambauwens** [comment] 2016-09-21 12:06
Oh I just assumed Automapper was now slow at startup because of the compilation thing, I didn't think it was something to do with our mappings. I'll see if I can nail it down to a repro project.

**Comment by lbargaoanu** [comment] 2016-09-21 12:07
5-10s is practically forever :) First we need to know why and take it from there.

**Comment by jbogard** [comment] 2016-10-05 04:47
One quick way would be to call AssertConfigurationIsValid? I believe that executes all the maps. I think.

**Comment by sambauwens** [comment] 2016-10-06 14:49
`AssertConfigurationIsValid()` throws an `AutoMapperConfigurationException` almost instantly due to many unmapped properties, there's a whole bunch of them in our project. These are fields we didn't put in our ValueObjects (mapping target) because we didn't want to map them. Automapper doesn't complain about them when we call `Map`.

**Comment by jbogard** [comment] 2016-10-06 14:53
Wait, you don't call AssertConfigurationIsValid at any point? Not in a test or anything? That's dangerous, I wouldn't use AutoMapper at all without configuration validation. That was the #1 reason why I built AutoMapper.

**Comment by kopfsick** [comment] 2016-10-13 14:13
Struggling with the same issue I think.
Using AutoMapper with some complex and deep mappings on our web-api. The first request takes 5-10 seconds and makes memory temporarily jump ~2 GB. If we hit the newly rebooted web-api with a concurrency test with 50 concurrent requests, the memory crawls up to ~30GB and everything just stops.
Tried invoking the `AssertConfigurationIsValid()` but that did not seem to do anything. However, performing a single map in the bootstrapper seemed to "get things ready" for the 50 request test.
Another set of weird observations is that all that consumed memory is marked as unmanaged, and if we switch the IIS over to 32-bit everything regarding memory seems fine...

What does AutoMapper exactly do when it maps for the first time? And is a concurrent/parallell "first-time-map" scenario supported/thought of?

**Comment by lbargaoanu** [comment] 2016-10-13 14:18
You need to profile it. Guessing won't do.

**Comment by lbargaoanu** [comment] 2016-10-13 14:35
@jbogard I have no idea whether that's an issue in real life, but maybe lock when compiling? Because now there's a race and compiling could happen more than once, depending on how long it takes.

**Comment by jbogard** [comment] 2016-10-13 15:15
A race on what though? We only compile each expression once.

@kopfsick does that concurrency match what you do at runtime? You have 50 hitting it at once after startup? What does that mapping look like?

AutoMapper just compiles a lambda expression. The expression is already built, we're just calling "Compile". But without seeing your mapping I can't really reproduce it.

**Comment by kopfsick** [comment] 2016-10-13 16:28
We've profiled it with ANTS, but since it just shows up as unmanaged memory we hit a dead end. Maybe I'm just not skilled enough with ANTS, is there some way to see what's actually going on?

That concurrency test is potentially a scenario we could face in production yes, we're still a couple of months away from first release to the customer. We could of course make sure to invoke every map once right after boot, but that creates some rather uncomfortable code imho.

The mappings are, as mentioned, quite deep and complex and parts of it involves a great deal of Condition(), ConvertUsing() and ResolveUsing() with varying degree of complexion. I'm not allowed to post any of it here, but it's roughly 1-2k lines of mapping code in our profiles combined.

I can see that there probably ends up being a race on the expression compilation. But a race that doesn't end in deadlocks, just enormous amounts of duplicated compiled expressions in memory. Which of the duplicates that ends up being persisted in the configuration is anyones guess.

Does the `AssertConfigurationIsValid()` actually compile the expressions? Away from code right now, I'll investigate more tomorrow.

**Comment by lbargaoanu** [comment] 2016-10-13 17:06
@jbogard No, we don't :) If 10 threads happen to try the first map, some of them will compile concurrently, because they might be inside the GetAdd factory at the same time.
@kopfsick What I'm talking about applies to one given map. That doesn't seem like a realistic scenario. It seems more likely that different maps are compiled concurrently and to prevent that you should compile them before time.

**Comment by jbogard** [comment] 2016-10-13 17:06
No it looks like AssertConfigurationIsValid does not compile expressions.

If the mapping config is as complex as you say, I doubt compiling all at once would make things better. MVC for example only compiles expressions in Razor the first time that page is hit. That's why when we do profiling we warm up the pages with a request before testing with load.

What is it like for just one request hitting the page for the first time? Rather than ANTS have you looked at JetBrains DotTrace? That's what I use.

**Comment by lbargaoanu** [comment] 2016-10-13 18:37
@kopfsick It's easier to profile for CPU, probably that's where the allocations come from. If most of the time is in Compile, then you need to determine what maps get compiled and if they overlap.

**Comment by kopfsick** [comment] 2016-10-14 08:29
Thanks for all feedback, I think I'm getting a clearer picture now.

I think its definitely a "race" in creating and compiling the mapper funcs into the `_mapPlanCache` dictionary in `MapperConfiguration` when we're hitting the api concurrently for the first map. Compiling all expressions multiple times concurrently combined with the fact that our expressions are complex is just heavy and requires a lot of memory and CPU. 
Simplifying our custom expressions and maybe using `IValueResolver` and `ITypeConverter` more instead of complex funcs in `ResolveUsing()`s could probably help. That would make the expressions smaller and easier to compile, right?

@jbogard The first request, which hits an endpoint that requires one of the complex mappings, takes approx 5-10 seconds with a memory usage of approx 2GB. Subsequent requests is, except DB operations, almost insignificant in both time, CPU and memory.

And regarding DotTrace/DotMemory, I haven't tried it even though i have the complete R# Ultimate license. Will try it soon now though :)

We did try to initiate compilation of all typemaps in our bootstrapper, but it didn't seem to work, altough I don't understand why:

`var typeMaps = config.GetAllTypeMaps();`
`foreach (var typeMap in typeMaps)`
`{`
`    var func = config.GetUntypedMapperFunc(new MapRequest(typeMap.Types, typeMap.Types));`
`}`

That code should, as I see it, perform the same operations that would be performed when we invoke
`_mapper.Map<TDestination>(sourceObject);`

**Comment by lbargaoanu** [comment] 2016-10-14 08:40
You shouldn't have to change your code. Compiling expressions should be faster than compiling C#. The concurrency issue, we can fix, If after this, compiling still takes more than a few hundred milliseconds, then there is a problem. And if we can't help, MS should be able to.

**Comment by lbargaoanu** [comment] 2016-10-14 09:04
#1734 solves the concurrency issue.

**Comment by kopfsick** [comment] 2016-10-14 10:18
That should force a single compilation yes :)
I think we'll have to perform some warmup-mappings in our bootstrapper and/or manually warm it up after a reboot until we can get this fix in.

Still, our first non-concurrent map takes several seconds for the most complex mappings we have. Another mapping configuration part which is similar in depth as the most complex one, but much more straight-forward with very little custom resolving seems to compile quite fast. So I can't help thinking that the size and complexity of our mappings affect the compilation time, and that I should consider having a refactoring done. But, so much to do and so little time...

Thanks anyway for helping me understand the behavior and making that PR :)

**Comment by hakant** [comment] 2016-11-08 15:37
I'm having a similar issue where a probably complex and deep mapping (I can share more details if necessary) takes around 5-10 seconds trying to allocate more than 5gb of memory and ends up in an OutOfMemory exception on a server with 8gb ram. 

Stack trace looks like following:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at AutoMapper.MapperConfiguration.MapperFuncs..ctor(MapRequest mapRequest, LambdaExpression typedExpression)
   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.MapperConfiguration.GetMapperFunc[TSource,TDestination](TypePair types)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TSource,TDestination](TSource source)
```

I've come across this issue after upgrading AutoMapper from 3.x.x to 5.1.1. Version 3 doesn't cause any surge in memory usage while with 5.1.1 first mappings usually surge memory usage and one of the mappings causes an OutOfMemoryException.

I don't know why it thinks it needs so much memory while V3 doesn't have that behavior for the same mapping. Btw, this is a test environment where I'm the only user, so there must be something other than concurrency going on here..

**Comment by lbargaoanu** [comment] 2016-11-08 15:41
A repro would help. Make a gist that we can execute and see fail.

**Comment by hakant** [comment] 2016-11-08 15:44
It's a deep nested domain model of a banking application. I'll see what I can do.

**Closed** 2016-11-18 17:34 UTC
Labels: Feature

**Comment by jbogard** [comment] 2016-11-18 21:30
Just as a benchmark, I tested this on my laptop with a client application with > 300 map definitions, and it compiled those mappings in 1.8 seconds.

**Comment by lbargaoanu** [comment] 2017-01-03 16:02
A complex model will result in a complex execution plan and that's the cause of the perf issue. I'd say a complex model is a problem in itself. But, if changing it is not an option, [DoNotInline](https://github.com/AutoMapper/AutoMapper/blob/e5cde15cdf9895950654a8b784e435d36a94481d/src/AutoMapper/IMemberConfigurationExpression.cs#L19) can help. It will allow you to not inline a member and this will simplify the execution plan. This will probably make the mapping itself slower (but compiling the execution plan will be faster), so use it wisely :) You might want to know exactly what [your mapping does](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping) at runtime.

**Comment by cryo75** [comment] 2017-03-13 12:05
I've tried DoNotInline, PreserveReferences and MaxDepth(1). Mapping a simple class (5 primitive properties and 3 empty collections) in the latest version (including myget prerelease) doubles memory usage and takes minutes to finish. Version 4.2.1 has no problem whatsoever.

So what did change so drastically that I can't upgrade to the newest release?

**Comment by lbargaoanu** [comment] 2017-03-13 12:12
These settings are unrelated. A repro would help. Make a gist that we can execute and see fail.

**Comment by jbogard** [comment] 2017-03-13 13:26
@cryo75 can you open a new issue?

**Comment by lbargaoanu** [comment] 2017-03-13 13:35
@jbogard He did, but I closed it because it seems to me to be the exact old issue. What makes you think it's different?

**Comment by cryo75** [comment] 2017-03-13 13:41
@lbargaoanu @jbogard I will try to create a gist but the object is quite complex and I'm trying to keep it simple. It might be related to ICollection but I'm still not sure.

**Comment by lbargaoanu** [comment] 2017-03-13 13:45
@cryo75 Please post in the new issue from now on. I'll reopen it if it's something new.
