### ISSUE TITLE
ProjectTo mapping nullable enums don't work

### ISSUE THREAD

**Issue by petrkasnal** [AutoMapper/AutoMapper#4301] opened 2023-06-07 13:53 UTC
Hi,

I ran into a problem in ProjectTo. If I have a class Class1 in which I have a nullable enum and another some Dto1 to which I want to map Class1, everything works as it should. Whether the enum is nullable in one, the other or both. But if I use ProjectTo, the mapping only works if both enum properties are set to not nullable. If one or both are null, it throws an error. Does anyone know about this? Alternatively, how can this be fixed? Additionally, I found out that if the enum is stored as a string instead of int in the db, it also gets bothered. Thank you very much in advance  

Here is discusion about same bug in OData extension which use ProjectTo: https://github.com/AutoMapper/AutoMapper.Extensions.OData/issues/181

`var items = repository.All().ProjectTo<Dto1>(_mapper.ConfigurationProvider);`

'Unable to create a map expression from CheckStateType (System.Nullable1[StateType]) to Nullable1.UI.StateType (System.Nullable`1[Domain.StateType])'

**Comment by lbargaoanu** [comment] 2023-06-07 14:13
Duplicate of https://github.com/AutoMapper/AutoMapper/issues/4295

**Closed as completed by lbargaoanu** 2023-06-07 14:13 UTC
