### ISSUE TITLE
Unexpectedly called mapping.

### ISSUE THREAD

**Issue by solo12zw74** [AutoMapper/AutoMapper#751] opened 2015-06-25 04:58 UTC
Hi there! The question is "Why mapping calls unexpectedly when i dont call it?". I hope my sample code illustrate it better than any words

```c#
class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap<DtoChild, DoChild>()
                .ForMember(doChild => doChild.CommonClassProperty, dtoChild => dtoChild.ResolveUsing<DtoChildToDoChildResolver>());

            Mapper.CreateMap<DtoClass, DoClass>()
                .ForMember(@do => @do.DoChildren, dto => dto.ResolveUsing<DtoToDoChildResolver>());

            Mapper.CreateMap<DoChild, DoChild>()
                .BeforeMap((s, d) => Console.WriteLine("2. Then <DoChild, DoChild> mapping called unexpectedly"))
                .ForMember(@do => @do.CommonClassProperty, dto => dto.Ignore());

            var source = new DtoClass
            {
                Id = 0,
                DtoChildren = new List<DtoChild> { new DtoChild { CommonClassPropertyName = "DtoChild1" } }
            };

            var dest = Mapper.Map<DtoClass, DoClass>(source);

            dest.DoChildren.ForEach(c => Console.WriteLine("3. And after unexpected call of <DoChild, DoChild> mapping CommonClass property is {0}", c.CommonClassProperty ?? (object)"null"));
            Console.WriteLine("4. The question is \"Why <DoChild, DoChild> calls?\"");

            Console.ReadKey();
        }


        public class DtoClass
        {
            public int Id { get; set; }
            public List<DtoChild> DtoChildren { get; set; }
        }

        public class DtoChild
        {
            public string CommonStringName { get; set; }
            public string CommonClassPropertyName { get; set; }

        }

        public class DtoToDoChildResolver : ValueResolver<DtoClass, List<DoChild>>
        {
            protected override List<DoChild> ResolveCore(DtoClass source)
            {
                var result = Mapper.Map<List<DtoChild>, List<DoChild>>(source.DtoChildren);
                foreach (var child in result)
                {
                    Console.WriteLine("1. After calling \"DtoToDoChildResolver\" CommonClassPropertyName is \"{0}\" (as expected)", child.CommonClassProperty.CommonClassPropertyName);
                }
                return result;
            }
        }

        public class DtoChildToDoChildResolver : ValueResolver<DtoChild, CommonClass>
        {
            protected override CommonClass ResolveCore(DtoChild source)
            {
                return new CommonClass { CommonClassPropertyName = source.CommonClassPropertyName };
            }
        }

        public class CommonClass
        {
            public string CommonClassPropertyName { get; set; }
        }

        public class DoClass
        {
            public int Id { get; set; }
            public List<DoChild> DoChildren { get; set; }
        }

        public class DoChild
        {
            public string CommonStingName { get; set; }
            public CommonClass CommonClassProperty { get; set; }
        }

    }
```

Output:
> 1. After calling "DtoToDoChildResolver" CommonClassPropertyName is "DtoChild1" (as expected)
> 2. Then `<DoChild, DoChild>` mapping called unexpectedly
> 3. And after unexpected call of `<DoChild, DoChild>` mapping CommonClass property is null
> 4. The question is "Why `<DoChild, DoChild>` calls?"

What am i doing wrongWhat do i wrong?

**Comment by lbargaoanu** [comment] 2015-06-25 13:42
It does look like a bug. It works with
            Mapper.CreateMap<DtoClass, DoClass>()
                .ForMember(@do => @do.DoChildren, dto => dto.MapFrom(s=>s.DtoChildren));

**Comment by lbargaoanu** [comment] 2015-06-25 14:33
Another thing that works below. So perhaps not exactly a bug.

            Mapper.CreateMap<DtoClass, DoClass>()
                .ForMember(@do => @do.DoChildren, dto => dto.MapFrom(s=>s.DtoChildren));

**Comment by lbargaoanu** [comment] 2015-06-25 16:32
I would say it's by design. What you return from the resolver gets mapped again for the final result. You return DoChild that gets mapped through the respective map. You would think that the resolver returns the final value, but it doesn't :) Perhaps @jbogard has a more useful answer.

**Comment by solo12zw74** [comment] 2015-06-26 04:22
> @lbargaoanu 
> It does look like a bug. It works with without Mapper.CreateMap< DoChild, DoChild >(). Do you really need that?

We find it too, but we really need this mapping in other parts of our app.

So i hope @jbogard find a time to look on it.

**Comment by jbogard** [comment] 2015-07-08 18:19
Yep, what gets returned from a resolver gets mapped again. Because you could resolve some other thing and expect it to get re-mapped. A resolver is really about "resolve a source value to map to the destination value" not "resolve a source value to SET on the destination value".

What you really want is a type converter, not value resolver. Type converters are about setting a value.

**Comment by lbargaoanu** [comment] 2015-07-08 19:25
@solo12zw74 Can you please close this?

**Closed** 2015-07-26 16:32 UTC
