### ISSUE TITLE
Wrong value is passed to ForAllMembers - Condition - default value of conventionally mapped nullable source to non-nullable destination, instead of source null

### ISSUE THREAD

**Issue by rehoutm** [AutoMapper/AutoMapper#1921] opened 2017-01-24 14:46 UTC
When source has a nullable type (DateTime?) with null value, and destination has a non-nullable type (DateTime), then Condition callback in ForAllMembers is passed default DateTime instead of null, as source member.

This behaviour makes it impossible to "by default" ignore null values mapping to non-nullable types. This is not a really good beahivour, e.g. "CreatedAt" property, which may be (and in this particular case it is) initialized in default constructor.

The code is reproduced like:

```
        public class DTO
        {
            public DateTime? Created { get; set; }
        }

        public class DestEntity
        {

            public DestEntity()
            {
                Created = DateTime.Now;
            }
            public DateTime Created { get; set; }
        }

        public static class Extensions
        {
            public static IMappingExpression<TSource, TDestination> IgnoreNulls<TSource, TDestination>(this IMappingExpression<TSource, TDestination> expression)
            {
                expression.ForAllMembers(opt =>
                {
                    opt.Condition((src, dest, srcMember, destMember, ctxt) =>
                    {
                        return srcMember != null;
                    });
                });
                return expression;
            }
        }
```

The srcMember is never null, it is always the default DateTime...
It is probably somehow connected to https://github.com/AutoMapper/AutoMapper/issues/1428

**Comment by lbargaoanu** [comment] 2017-01-24 15:28
Duplicate of #1912.

**Closed by lbargaoanu** 2017-01-24 15:28 UTC

**Comment by rehoutm** [comment] 2017-01-24 15:42
How exactly am I gonna solve this with PreCondition, when I cannot check source value with ForAllMembers?

Also ForAllPropertyMaps is not really an option since I want this to be an opt-in for given type-maps, not used for all mappings.

**Comment by lbargaoanu** [comment] 2017-01-24 15:49
As it says over there, ForAllPropertyMaps takes a filter.

**Comment by rehoutm** [comment] 2017-01-24 16:10
I don't really take it as a solution, it is more of an ugly hack... For hundreds of type-maps, it takes a LOT of work and refactoring, just because PreCondition does not have the overloads needed to pull this off...

**Comment by lbargaoanu** [comment] 2017-01-24 16:19
No, if you apply it sensibly, it should just work. You shouldn't have to change individual maps. I'm not sure that PreCondition overload is as easy as it seems. A PreCondition runs before resolving the source property value, so it cannot receive it as parameter. I'm sure it could work somehow, but that's hackish too. Feel free to try it.

**Comment by rehoutm** [comment] 2017-01-24 16:35
You shouldn't have to actually resolve the source value, just read it, which is a different thing, if I understand correctly the concept of resolving in AutomApper...

**Comment by jbogard** [comment] 2017-01-25 20:58
Yeah, we don't really need another PreCondition overload.

**Comment by rehoutm** [comment] 2017-01-30 08:54
The thing is, that without the overload, it is overly complicated, to mimic following kind of behaviour from previous (e.g. 3.x) versions:

"If the source property is null, and the destination property is non-nullable, keep the destination value"

Which is particularly useful in the scenarios I described originally - e.g. a "read-only" CreatedAt DateTime field, particularly when the same class/DTO is used for both data input and output mapping (reverse mapping).
