### ISSUE TITLE
Possible bug with interface inheritance using ConstructProjectionUsing()

### ISSUE THREAD

**Issue by DigTK** [AutoMapper/AutoMapper#1673] opened 2016-09-07 20:45 UTC
Hi everyone, here's a gist of my problem code:

https://gist.github.com/DigTK/1131344e19ab64b16017a14b32354837

AutoMapper nuget package version is 5.1.1

`AssertConfigurationIsValid` throws no errors, yet when running the unit test it fails the `Assert()` because `BaseTestProperty` is 0 instead of 10. It doesn't seem to properly map the inherited `ITestBase` yet it maps the inherited `ITestDetail` just fine.

Did I do a dumb inheritance/mapping mistake or is that a bug in AutoMapper?

**Comment by lbargaoanu** [comment] 2016-09-08 08:16
You map ITestDetail, so BaseTestProperty is actually unmapped. You explicitly map the interface, so there's no error to report. That's expected behavior.

**Comment by lbargaoanu** [comment] 2016-09-08 09:19
Instead of ConstructProjectionUsing (which should be ConstructUsing unless you use Project) you can try mapping into an existing instance.

**Comment by DigTK** [comment] 2016-09-08 13:46
I'm not sure I understand, can you please provide an example of what you mean with mapping into an existing instance? Google failed me :(

**Comment by lbargaoanu** [comment] 2016-09-08 13:50
I simply mean passing the destination when mapping instead of that trick you have.

     Mapper.Map(source, destination);

**Comment by DigTK** [comment] 2016-09-08 14:17
Oh I see, but that would defeat the whole purpose why I'm doing this. The gist I provided above is only a bare bones version of the problem I'm having, in my actual project the class provided above is being used for a property in an overarching class, complete with generics and everything. The point of me trying to do this is so that I don't have to explicitly point out what the destination class is but that it can automatically derive it from a property in the source class.

Here is basically what I'm trying to do, extending the code in the gist:
`public interface IExtensionBase<TTest>
where TTest : ITest
{
  int someProperty { get; set; }
  IList<TTest> Stuff { get; set; }
}`

If I'm not completely mistaken, if I now go ahead and map my `IExtensionBase` there's no chance to actually supply a target destination for my `ITest` so it would have to resolve itself automatically by just having a configured map in place.

**Comment by lbargaoanu** [comment] 2016-09-08 14:25
I don't think it would. You just have to put the factory code elsewhere and pass the result to AutoMapper. That code you have in ConstructUsing does not influence the map used, but if you pass in the destination, that does.

**Comment by lbargaoanu** [comment] 2016-09-08 15:19
You can also [play games](https://gist.github.com/lbargaoanu/ed96a881399d4b0a8b37c994760541e4#file-mapintodestination), but this seems unwarranted.

**Comment by DigTK** [comment] 2016-09-08 15:52
Mapping it inside the `ConstructUsing()` did the trick, thanks for your help!

**Comment by lbargaoanu** [comment] 2016-09-08 16:36
Trick is the keyword here :) Anyway, you can close the issue.

**Comment by TylerCarlson1** [comment] 2016-09-08 19:20
@lbargaoanu There was a request to do Includes based on properties inside the source a long time ago.
If I remember correctly it was also to be used in Projection which EF couldn't handle different return types, so it was never seriously considered.

**Comment by lbargaoanu** [comment] 2016-09-08 19:38
@TylerCarlson1 I think I remember something too. But this seems different. It's more about when the map gets resolved (Includes or no Includes). At map time :) ConstructUsing is to late to matter. Related I guess.

**Comment by TylerCarlson1** [comment] 2016-09-08 19:49
yea but if you could include using source properties you would do that and it would solve the same problem.  But it's not available currently, so you resort to ConstructUsing/ConvertUsing

**Comment by DigTK** [comment] 2016-09-08 23:00
@lbargaoanu I figured I'd leave this issue open for a bit longer to see if anyone else may have another solution. Your trick works but it kind of doesn't seem optimal. I'd rather have an `Include()` or something instead of mapping inside another mapping, that seems kinda hacky. But if that's not possible then I'll have to go with this for now.

**Comment by lbargaoanu** [comment] 2016-09-09 08:33
It's a hack, because Include doesn't work the way you would like it to work. Map resolving works with types, not with random conditions. The clean solution is to have a factory and pass the destination in, let resolving do its thing. And then you don't need Include at all. The wrong tool for the job.

**Comment by DigTK** [comment] 2016-09-09 12:58
But even with a factory you'd still be mapping inside a `CreateMap()` wouldn't you? You'd just be doing it through an external method. Or am I misunderstanding where that factory would be?

**Comment by lbargaoanu** [comment] 2016-09-09 13:08
No. You just pass the destination to Map and it will choose the right map because it has both source and destination types. The factory method would have nothing to do with AutoMapper. Whatever works for you.

**Closed** 2016-09-20 13:07 UTC
