### ISSUE TITLE
Auto-selecting child class even if you map from the parent one

### ISSUE THREAD

**Issue by mangelarilla** [AutoMapper/AutoMapper#912] opened 2015-10-02 13:02 UTC
I'm not sure if it's an issue, but it could be a misleading behaviour (imo).
Consider the following scenario:
```
public class BaseItem {}....
public class ItemA : BaseItem {}...
```
and both mapped to the same object:
```
Mapper.CreateMap<BaseItem,RandomDTO>();
MapperCreateMap<ItemA,RandomDTO>();
```
We got a generic method where we use a map like this `...Map<BaseItem,RandomDTO>` and this method can receive either the base or any of its implementations.

It turns out that when receiving a child object as input,  instead of getting the base map as we specified in code, it's going for the child map. I guess this is usually not a problem, but it proved to be inconvenient for debugging.

**Comment by jbogard** [comment] 2015-10-06 12:32
I believe this is fixed in the 4.1 pre-release packages. My build server is borked right now, however so you might not be able to confirm just yet.

**Comment by lbargaoanu** [comment] 2015-10-07 13:22
The same as #910.

**Comment by lbargaoanu** [comment] 2015-10-09 09:38
@jbogard Not so fast :) I think this happens because we use the runtime type to find the TypeMap. So not a bug in my opinion.

**Comment by jbogard** [comment] 2015-10-12 18:57
Build server is fixed! @lbargaoanu @TylerCarlson1 huzzah

beta7 of DNX killed everything, had to force beta 6

**Comment by TylerCarlson1** [comment] 2015-10-12 19:38
Hopefully that's the last Automapper see's of DNX issues. ...

**Comment by jbogard** [comment] 2015-10-12 19:42
![jim-carrey-rindo](https://cloud.githubusercontent.com/assets/104498/10436938/7d90945c-70ef-11e5-9dd2-abe829f547a4.gif)

**Closed** 2015-10-21 14:05 UTC
Labels: Bug
