### ISSUE TITLE
Some mappings stopped working after upgrade to 6.2.x

### ISSUE THREAD

**Issue by ermac0** [AutoMapper/AutoMapper#2435] opened 2017-11-28 12:05 UTC
After upgrading from 6.1.1 to 6.2.1 we've noticed that some mappings started generating exceptions.

`Unable to cast object of type 'System.Collections.Generic.HashSet`1[DataAccess.EntityB]' to type 'System.Collections.Generic.List`1[DataAccess.EntityB]'`

We're trying to map entity (EntityA) to a DTO (DtoA). That entity has navigation properties (zero-to-many) of type `HashSet<EntityB>` which map to corresponding `IEnumerable<DtoB>` properties on the DTO. It's working fine with `6.1.1`.

The strange thing is the mapping works for some properties but fails for others. I wasn't able to create an isolated gist to replicate the problem.

The same problem exists in 6.2.0

**Comment by lbargaoanu** [comment] 2017-11-28 12:10
Duplicate of #2397.

**Closed by lbargaoanu** 2017-11-28 12:10 UTC

**Comment by ermac0** [comment] 2017-11-28 12:19
#2397 is closed, does it mean there won't be a proper fix for it?

**Comment by lbargaoanu** [comment] 2017-11-28 12:20
No. You either specify the concrete types, or you set UseDestinationValue.
