### ISSUE TITLE
Mapper.CreateMap<Self, Self> ignores nullability rules on collection properties

### ISSUE THREAD

**Issue by Serenyrddraig** [AutoMapper/AutoMapper#618] opened 2014-10-30 19:18 UTC
This issue arose because my developer reused a Type between two DTOs. Consider the model

        public class Container
        {
            public List<string> Items { get; set; }
        }
        class ContainerDto
        {
            public List<string> Items { get; set; }
        }
        class Holder
        {
            public Container[] Containers { get; set; }
        }
        class HolderDto
        {
            public ContainerDto[] Containers { get; set; }
        }

The rule I must enforce is that if the Items collection in the source is null, it must not be null in the destination. I can do this in a variety of ways, some of which are shown in the following test.

        [Fact]
        public void test_mapping_withNullToInstanceProperty()
        {
            Mapper.AllowNullDestinationValues = false;
            Mapper.CreateMap<Holder, HolderDto>();
            Mapper.CreateMap<Container, ContainerDto>()
                //.ForMember(d =>d.Items, o=>o.NullSubstitute(new List<string>()))
                //.ForMember(d => d.Items, o => o.MapFrom(s => s.Items ?? new List<string>()));
                ;

            var from = new Holder() { Containers = new Container[] { new Container() { Items = null } } };
            var to = Mapper.Map<HolderDto>(from);
            Assert.NotNull(to.Containers.First().Items);
        }

However, the situation that my developer had created effectively is

        [Fact]
        public void test_mapping_withNullToInstanceProperty()
        {
            Mapper.AllowNullDestinationValues = false;
            Mapper.CreateMap<Holder, Holder>();
            Mapper.CreateMap<Container, Container>()
                //.ForMember(d =>d.Items, o=>o.NullSubstitute(new List<string>()))
                //.ForMember(d => d.Items, o => o.MapFrom(s => s.Items ?? new List<string>()));
                ;

            var from = new Holder() { Containers = new Container[] { new Container() { Items = null } } };
            var to = Mapper.Map<Holder>(from);
            Assert.NotNull(to.Containers.First().Items);
        }

No combination of techniques I have tried produce the desired result, i.e. the destination Items collection remains null after mapping. The configuration does not assert as invalid.

Sadly for me this occurred in a very complex object where the outermost types were different but this situation occurred in properties within those objects.

**Comment by lbargaoanu** [comment] 2015-07-13 13:52
@jbogard I believe AssignableArrayMapper exists so in a case like this, the Container array is not mapped item by item and is simply assigned to the destination. So maybe close this as "by design"? A workaround is to use another collection type, not an array.

**Comment by jbogard** [comment] 2015-07-13 13:56
Pretty much yeah. AutoMapper isn't a cloning library, but there's something wonky here I think - if you create a map it should trump assigning.

**Comment by jbogard** [comment] 2015-07-17 13:07
Fixed

**Closed by jbogard** 2015-07-17 13:07 UTC
Labels: Bug

**Comment by Serenyrddraig** [comment] 2015-07-17 15:25
Thanks!
