### ISSUE TITLE
AutoMapper 4 targeting wrong constructor on instantiation

### ISSUE THREAD

**Issue by btwalleye** [AutoMapper/AutoMapper#847] opened 2015-08-21 15:47 UTC
After updating to AutoMapper 4, I am receiving an error in a situation that used to work.  I have 2 different objects that I am trying to create a mapping for (ImportedContact -> Contact).  The destination object (Contact) has 2 constructors, one without parameters and another with 2 reference type parameters (SerializationInfo, StreamingContext).  When I try calling Mapper.Map to instantiate a new instance of the destination object (Contact) it is calling the constructor that takes 2 parameters.  AutoMapper 3 was using the parameter-less constructor.  This causes the following error:

    "Missing type map configuration or unsupported mapping.

    Mapping types:
    ImportedContact -> SerializationInfo
    SharePointDirectory.Jobs.ImportedContact -> System.Runtime.Serialization.SerializationInfo

    Destination path:
    Contact

    Source value:
    SharePointDirectory.Jobs.ImportedContact"

Here is a link to some files that I have uploaded to Gist that can be put into a Console app and when ran will demonstrate the issue.  https://gist.github.com/ristogod/60ac506272bdd519485a

**Comment by sickboy** [comment] 2015-08-21 15:55
I can confirm this issue

**Comment by lbargaoanu** [comment] 2015-08-24 12:18
Probably fixed by #816.

**Comment by sgwatgit** [comment] 2015-08-27 21:03
I've also just run into this issue. The class being mapped to has a constructor with no parameters, one that takes `(SerializationInfo info, StreamingContext context)` and one that takes `(DataRow dr)`.

AutoMapper v4 is trying to map to the constructor that is taking `(SerializationInfo info, StreamingContext context)` instead of the empty constructor.

This did not occur with AutoMapper v3.x

**Comment by ristogod** [comment] 2015-08-27 21:30
Same. I think they fixed this, but it hasn't been released yet???

**Comment by jbogard** [comment] 2015-08-27 21:49
It's on the pre-release MyGet feed.

**Comment by TylerCarlson1** [comment] 2015-08-27 22:08
How many more new issues saying the same thing about this problem do we need to have before it gets patched?

**Comment by jbogard** [comment] 2015-08-28 13:57
@TylerCarlson1 eleventy.

**Comment by MartinTherriault** [comment] 2015-09-02 13:21
I have this issue as well. I found a work around with "ConstructUsing" function, but since I would have to do this with 20+ mapping expressions I'll wait for next release.

**Closed** 2015-09-03 13:30 UTC

**Comment by HaukiDog** [comment] 2015-09-19 15:06
I am trying to work around this error with a ConstructUsing statement, but it does not compile. I'm going to wait for the fix as well, but I wanted to include this here as it may or may not be useful, but here's some code which could be used for a simple unit test to check for this error. Any insight in to why the ConstructUsing clause does not compile would be great.

I've validated the below code works with pre 4.0 automapper.

-------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using AutoMapper;

namespace InterfaceNameSpace
{
    public interface ISomeInterface
    {
        string SomeInterfaceValue { get; set; }
    }
}

namespace ThatNameSpace
{
    public class ThatClass
    {
        public ThatClass()
        {
        }

        public string ThatValue { get; set; }
        public string ThatOtherValue { get; set; }
    }
}

namespace ThisNameSpace
{
    public class ThisClass
    {
        //commenting out this constructor eliminates error
        public ThisClass(InterfaceNameSpace.ISomeInterface x)
        {
            if (x != null)
            {
                SomeValue = x.SomeInterfaceValue;
            }
        }

        public ThisClass()
            : this(null)
        {
        }

        public string SomeValue { get; set; }
        public string ThisOtherValue { get; set; }
    }
}

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap<ThatNameSpace.ThatClass, ThisNameSpace.ThisClass>()
                //!!in theory this should fix it but it gives an ambiguous reference error
                //!!.ConstructUsing(x => new ThisNameSpace.ThisClass())
                .ForMember(x => x.SomeValue, x => x.MapFrom(t => t.ThatValue))
                .ForMember(x => x.ThisOtherValue, x => x.MapFrom(t => t.ThatOtherValue));

            var source = new ThatNameSpace.ThatClass()
            {
                ThatValue = "a",
                ThatOtherValue = "b"
            };

            var destination = Mapper.Map<ThisNameSpace.ThisClass>(source);

            Console.WriteLine(destination.SomeValue);
            Console.WriteLine(destination.ThisOtherValue);

        }
    }
}

**Comment by TimoTalasmaa** [comment] 2015-10-02 14:56
I had the same issue, took me like 4 hours to pin it down to Automapper invoking the wrong constructor. Also, the error message isnt very helpful, would be great if it could give more info about what went wrong.

**Comment by JozefKulla** [comment] 2015-10-06 07:34
Hi,
Try this:
<code>
Mapper.Configuration.DisableConstructorMapping();
</code>

**Comment by TimoTalasmaa** [comment] 2015-10-06 08:43
Thanks Jozef!
DisableConstructorMapping did not work for me. But googling around with that keyword led me to http://helpprogramming.xyz/question/26764022/automapper-ignore-issue and from that article I discovered that
Mapper.CreateMap<CableID, CableIDDTO>()
    .ConstructUsing((Func<CableID, CableIDDTO>)(src => new CableIDDTO()))

works for me
