### ISSUE TITLE
AutoMapper 5.2.0 breaks Enum to String mapping when value is 0

### ISSUE THREAD

**Issue by farlop** [AutoMapper/AutoMapper#1867] opened 2016-12-26 13:36 UTC
I think this is related to the fix for #1774. If an enum has a possible value with integer value equals to 0, the enum is not mapped and null string is returned. The following failing test can shows it:

```
[TestMethod]
public void TestParseOKFail()
{           
    var b = new A { Value = OKFailEnum.OK };
    var res = Mapper.Map<Result>(b);
    Assert.IsNotNull(res.Value);
}

enum OKFailEnum { OK = 0, Fail = 1 }
class Result { public string Value { get; set; } }
class A { public OKFailEnum Value { get; set; } }
```

If you change OK value from 0 to another value, the test will pass.

**Comment by lbargaoanu** [comment] 2016-12-26 14:03
Duplicate of #1862.

**Comment by lbargaoanu** [comment] 2016-12-28 15:37
This can be closed.

**Closed** 2016-12-29 12:55 UTC
