### ISSUE TITLE
Exceptions since 6.2.1

### ISSUE THREAD

**Issue by negberts** [AutoMapper/AutoMapper#2428] opened 2017-11-24 14:39 UTC
Hi,

With version 6.2.1 we are starting to receive these errors

```
Message of type AutoMapper.AutoMapperMappingException occurred: 
Error mapping types.

Mapping types:
Bouwstof -> Bouwstof
Pim.Models.Bouwstoffen.Bouwstof -> Pim.Repositories.EF.Bouwstof

Type Map configuration:
Bouwstof -> Bouwstof
Pim.Models.Bouwstoffen.Bouwstof -> Pim.Repositories.EF.Bouwstof

Property:
BouwstofSpecificaties
- Unable to cast object of type 'System.Collections.Generic.HashSet`1[Pim.Repositories.EF.BouwstofSpecificatie]' to type 'System.Collections.Generic.List`1[Pim.Repositories.EF.BouwstofSpecificatie]'.

   at lambda_method(Closure , Bouwstof , Bouwstof , ResolutionContext )
   at Pim.BouwstofServices.BouwstofService.<UpdateCurrentVersionInstance>d__156.MoveNext() in C:\Git\PIM\Pim.Solution
```

We are using a Service Fabric Stateless service, where in the class the mapper configuration is created:

```
/// <summary>
        /// The mapper
        /// </summary>
        private IMapper mapper;

        /// <summary>
        /// Gets a new instance of the mapper.
        /// </summary>
        private IMapper MapperInstance
        {
            get
            {
                if (mapper == null)
                {
                    MapperConfiguration config = new MapperConfiguration(cfg =>
                    {
                        cfg.AddProfile(new Repositories.MappingProfile(TenantName));
                        cfg.AddProfile(new AzureSearch.MappingProfile());
                        cfg.AddProfile(new MappingProfile(TenantName));
                    });

                    mapper = config.CreateMapper();
                }

                return mapper;
            }
        }
```

The mapping is created like this:
```
CreateMap<Models.Bouwstoffen.Bouwstof, Repositories.EF.Bouwstof>()
                .ForMember(d => d.BouwstofId, opt => opt.MapFrom(src => src.Id))
                .ForMember(d => d.BouwstofSoort, opt => opt.Ignore())
CreateMap<Models.Bouwstoffen.BouwstofSpecificatie, EF.BouwstofSpecificatie>()
                .ForMember(d => d.BouwstofSpecificatieId, opt => opt.MapFrom(src => src.Id))
                .ForMember(d => d.Documents, opt => opt.Ignore());
```

And then in our method we call

```
// apply the changes to the original entity (update)
bouwstofEntity = MapperInstance.Map(newBouwstof, bouwstofEntity);
```

This used to work, but is not working anymore...  What are we doing wrong? This used to work without any problem on 6.1.1 and earlier...

**Comment by negberts** [comment] 2017-11-24 14:43
The strange thing is that it is trying to cast the hashset to the list while the hashset is on the target (entity framework) class and the list is on the source class...

**Comment by negberts** [comment] 2017-11-24 14:48
So, I figured something out.. If we are mapping like this:

`bouwstofEntity = MapperInstance.Map<Repositories.EF.Bouwstof>(newBouwstof);`

instead of 
`
bouwstofEntity = MapperInstance.Map(newBouwstof, bouwstofEntity);`

No errors are thrown...

**Comment by lbargaoanu** [comment] 2017-11-24 14:59
Duplicate of #2397.

**Closed by lbargaoanu** 2017-11-24 14:59 UTC

**Comment by negberts** [comment] 2017-11-24 15:03
@lbargaoanu #2397 is closed and the workaround is not working for us... Or is there gonna be a fix in 6.2.2?

**Comment by lbargaoanu** [comment] 2017-11-24 15:13
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by negberts** [comment] 2017-11-24 15:24
Here it is:

https://gist.github.com/negberts/55f9680ddcfe04ac88add9d2f73a5031

**Comment by negberts** [comment] 2017-11-24 15:25
Note that dest = mapper.Map(source); doesn't give the error.

**Comment by lbargaoanu** [comment] 2017-11-24 15:29
And of course it works with UseDestinationValue.

**Comment by negberts** [comment] 2017-11-24 15:34
Yes, but we have about +500 tables in our database, all with an average of 4-5 foreign keys. Do you really want me to add this line for all these foreign keys that lead to hashsets?

**Comment by jbogard** [comment] 2017-11-24 15:47
No use can use ForAllMembers and filter where it’s a HashSet.
