### ISSUE TITLE
Weird problem in v1.1.0.188

### ISSUE THREAD

**Issue by bramdebouvere** [AutoMapper/AutoMapper#699] opened 2015-03-26 16:50 UTC
Hello,

The previous version of our application still uses version v1.1.0.188 of the AutoMapper.
In that version, we *sometimes* have an issue when mapping (not always, it's very unpredictable).

We get the following error:
```
Trying to map OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult.
Using mapping configuration for OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.
```

This is the full Exception info:
```xml
<ExceptionDetail xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel">
  <HelpLink i:nil="true" />
  <InnerException>
	<HelpLink i:nil="true" />
	<InnerException>
	  <HelpLink i:nil="true" />
	  <InnerException>
		<HelpLink i:nil="true" />
		<InnerException>
		  <HelpLink i:nil="true" />
		  <InnerException i:nil="true" />
		  <Message>Unable to cast object of type 'OurNS.WebShop.Model.PlaceReservation' to type 'OurNS.WebShop.Model.RecurringPlaceReservation'.</Message>
		  <StackTrace>   at lambda_method(Closure , Object )
						at AutoMapper.Internal.PropertyGetter.GetValue(Object source)
						at AutoMapper.Internal.MemberGetter.Resolve(ResolutionResult source)
						at AutoMapper.PropertyMap.ResolveValue(ResolutionContext context)
						at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)</StackTrace>
		  <Type>System.InvalidCastException</Type>
		</InnerException>
		<Message>Trying to map OurNS.WebShop.Model.PlaceReservation to OurNS2.WebShop.WebServices.Contracts.RecurringPattern.
				Using mapping configuration for OurNS.WebShop.Model.RecurringPlaceReservation to OurNS2.WebShop.WebServices.Contracts.RecurringPlaceReservation
				Destination property: Pattern
				Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
		<StackTrace>   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)
						at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
						at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
						at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)</StackTrace>
		<Type>AutoMapper.AutoMapperMappingException</Type>
	  </InnerException>
	  <Message>Trying to map OurNS.WebShop.Model.RecurringPlaceReservation to OurNS2.WebShop.WebServices.Contracts.RecurringPlaceReservation.
				Using mapping configuration for OurNS.WebShop.Model.RecurringPlaceReservation to OurNS2.WebShop.WebServices.Contracts.RecurringPlaceReservation
				Destination property: ValidatedBasketItem
				Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
	  <StackTrace>   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
					at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)</StackTrace>
	  <Type>AutoMapper.AutoMapperMappingException</Type>
	</InnerException>
	<Message>Trying to map OurNS.WebShop.Model.RecurringPlaceReservation to OurNS2.WebShop.WebServices.Contracts.RecurringPlaceReservation.
			Using mapping configuration for OurNS.WebShop.Model.RecurringPlaceReservation to OurNS2.WebShop.WebServices.Contracts.RecurringPlaceReservation
			Destination property: ValidatedBasketItem
			Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
	<StackTrace>   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)
					at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
					at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
					at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)</StackTrace>
	<Type>AutoMapper.AutoMapperMappingException</Type>
  </InnerException>
  <Message>Trying to map OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult.
			Using mapping configuration for OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult
			Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
  <StackTrace>   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
				at AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType)
				at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source)
				at AutoMapper.Mapper.Map[TSource,TDestination](TSource source)
				at OurNS2.WebShop.WebServices.Server.Adapter.Map[TSource,TDestination](TSource source) in ***
				at OurNS2.WebShop.WebServices.Server.WebShopWebService.ValidateBasketItem(ValidateBasketItemRequest request) in ***
				at SyncInvokeValidateBasketItem(Object , Object[] , Object[] )
				at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)
				at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)
				at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)
				at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc&amp; rpc)
				at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)</StackTrace>
  <Type>AutoMapper.AutoMapperMappingException</Type>
</ExceptionDetail>

```

Our Mapping:
```c#
Mapper.CreateMap<BasketItem, DM.BasketItem>()
	.Include<RecurringPlaceReservation, DM.RecurringPlaceReservation>()
	.Include<OptionalRecurringPlaceReservation, DM.OptionalRecurringPlaceReservation>()
	.Include<PlaceReservation, DM.PlaceReservation>()
	.Include<OptionalPlaceReservation, DM.OptionalPlaceReservation>();
	
Mapper.CreateMap<RecurringPlaceReservation, DM.RecurringPlaceReservation>()
	.Include<OptionalRecurringPlaceReservation, DM.OptionalRecurringPlaceReservation>();
	
Mapper.CreateMap<PlaceReservation, DM.PlaceReservation>()
	.Include<RecurringPlaceReservation, DM.RecurringPlaceReservation>()
	.Include<OptionalRecurringPlaceReservation, DM.OptionalRecurringPlaceReservation>()
	.Include<OptionalPlaceReservation, DM.OptionalPlaceReservation>();

Mapper.CreateMap<RecurringPattern, DM.RecurringPattern>();
Mapper.CreateMap<OptionalPlaceReservation, DM.OptionalPlaceReservation>();
Mapper.CreateMap<RecurringPlaceReservationLockTicket, DM.RecurringPlaceReservationLockTicket>();
Mapper.CreateMap<PlaceReservationLockTicket, DM.PlaceReservationLockTicket>();
Mapper.CreateMap<RecurringPlaceReservationSalesItem, DM.RecurringPlaceReservationSalesItem>();
Mapper.CreateMap<PlaceReservationSalesItem, DM.PlaceReservationSalesItem>();

```

The objects inherit as follows:
```c#

[KnownType(typeof (RecurringPlaceReservation))]
[KnownType(typeof (OptionalRecurringPlaceReservation))]
[KnownType(typeof (PlaceReservation))]
[KnownType(typeof (OptionalPlaceReservation))]
[DataContract(Namespace = "***")]
[Serializable]
public abstract class BasketItem
{
	// some datamembers ...
}

[Serializable]
[DataContract(Namespace = Constants.Namespace)]
[KnownType(typeof(OptionalPlaceReservation))]
[KnownType(typeof(RecurringPlaceReservation))]
[KnownType(typeof(OptionalRecurringPlaceReservation))]
public class PlaceReservation : BasketItem, InterfaceX, InterfaceY
{
	// some datamembers ...
}

[Serializable]
[DataContract(Namespace = Constants.Namespace)]
[KnownType(typeof(OptionalRecurringPlaceReservation))]
public class RecurringPlaceReservation : PlaceReservation
{
	public RecurringPattern Pattern { get; set; }
	
	// some other datamembers ...
}

```

The objects basicly contain the same members in both models.

Using the AssertConfigurationIsValid does not throw an exception.
```c#
AutoMapper.Mapper.AssertConfigurationIsValid();
```

We map from the BasketItem to the BasketItem in the other model.
It looks like it is trying to map objects to the wrong type.

We cannot simulate this, it happens at random times in our production code.
Is this a known issue? Is there perhaps already a fix for this?

**Comment by jbogard** [comment] 2015-03-26 17:53
Yes, that version had threading issues. One workaround is to put a lock around your configuration.

**Comment by bramdebouvere** [comment] 2015-03-31 10:55
Thanks for your answer, Jimmy.

When we searched around for this issue, we found that some people had threading issues when they didn't use a static map. We, however, do use a static map.

In our global.asax of our webservice we call the Adapter.Configure in the following class:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using AutoMapper;

using OurNS2.WebShop.WebServices.Contracts;
using OurNS2.WebShop.WebServices.Contracts.Model;
using DM = OurNS.WebShop.Model;

namespace OurNS2.WebShop.WebServices.Server
{
    public static class Adapter
    {
        public static void Configure()
        {
            // Map from service contract model to domain model
			
			// Mapping forward
            Mapper.CreateMap<Basket, DM.Basket>();
			// .. + more CreateMap calls
			
			// Mapping backwards
            Mapper.CreateMap<DM.Basket, Basket>();
			// .. + more CreateMap calls
        }

        [DebuggerStepThrough]
        public static TDestination Map<TSource, TDestination>(TSource source)
        {
            try
            {
                return Mapper.Map<TSource, TDestination>(source);
            }
            catch (Exception e)
            {
                throw;
            }
        }

    }
}

```

After this, we do not create any more maps.
We use the Adapter.Map<...,...>() method to map objects at runtime.
Is it correct to suppose that there is a threading issue in the Mapper.Map method?

**Comment by jbogard** [comment] 2015-03-31 13:43
Specifically, the threading issue was with Mapper.CreateMap and Mapper.Map.

**Comment by bramdebouvere** [comment] 2015-04-01 10:41
Hello,

We tried to simulate the threading issues by executing the following code, but we did not manage to get any errors.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using OurNS.WebShop.Model;
using TestAdapterThreads.TestAdapterThreads;

namespace TestAdapterThreads
{
    class Program
    {
        static void Main(string[] args)
        {
            // set up and test adapter
            Adapter.Configure();
            if (Adapter.AssertMapperConfigurationIsValid() != "Adapter OK")
            {
                Console.WriteLine("Adapter error");
                return;
            }

            Console.WriteLine("Test started");
            Console.Write("Please wait.");

            Parallel.For(0, 1000000, i =>
            {
                if (i % 3000 == 0)
                    Console.Write(".");
				
                try
                {
                    var basket = CreateBasket();
                    var validationReulst = CreateBasketValidationResult();

                    var result2 = Adapter.Map<BasketValidationResult, OurNS2.WebShop.WebServices.Contracts.BasketValidationResult>(validationReulst);
                    var result = Adapter.Map<Basket, OurNS2.WebShop.WebServices.Contracts.Basket>(basket);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    Console.WriteLine(ex.StackTrace);
                }

            });

            Console.WriteLine(Environment.NewLine + "Test complete");
            Console.ReadLine();
        }

        private static Basket CreateBasket()
        {
            var basket = new Basket()
            {
                // some members ...
            };
            return basket;
        }

        private static BasketValidationResult CreateBasketValidationResult()
        {
            var result = new BasketValidationResult()
            {
                // some members ...
            };
            return result;
        }

    }
}
```
We would like to be able to simulate the issue, so we can be sure that updating will fix the issue.
Do you perhaps have an idea of how we could simulate this?

**Comment by jbogard** [comment] 2015-04-01 13:02
CreateMap was not thread safe.

**Comment by bramdebouvere** [comment] 2015-04-01 15:58
But we execute CreateMap in a static context at our application startup, so that can't be the issue, right?

**Comment by jbogard** [comment] 2015-04-01 17:05
You can have something executing Map while CreateMap gets executed, I'm not sure if ASP.NET blocks requests during this time.

**Comment by bramdebouvere** [comment] 2015-04-02 13:54
We have tested this by adding a *Thread.Sleep()* and some logging in our *Global.asax*. None of the requests are actually being processed before the code in *Application_Start* completes running.

As explained on [MSDN](https://msdn.microsoft.com/en-us/library/ms178473%28v=vs.100%29), you can see that the *Application_Start* in *Global.asax* is only called once, and before executing the HttpApplication pipeline. This confirms what we tested.
On top of that, we do not have multiple worker threads in IIS. Our WCF ConcurrencyMode however is set to Multiple, so requests are handled in multiple threads.

Knowing this, we are pretty certain that our *CreateMap()*s are only executed once. Requests that use the *Map()* function do run in multiple threads, but not before (or during) the creation of the mappings.

**Comment by bramdebouvere** [comment] 2015-05-04 08:57
Hello,

We updated our application to the new AutoMapper version, and we still see these same errors in our logging:

```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <Action xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none" s:mustUnderstand="1">http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher/fault</Action>
  </s:Header>
  <s:Body>
    <s:Fault>
      <faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:InternalServiceFault</faultcode>
      <faultstring xml:lang="nl">Trying to map OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult.
Using mapping configuration for OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</faultstring>
      <detail>
        <ExceptionDetail xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel">
          <HelpLink i:nil="true" />
          <InnerException>
            <HelpLink i:nil="true" />
            <InnerException>
              <HelpLink i:nil="true" />
              <InnerException>
                <HelpLink i:nil="true" />
                <InnerException>
                  <HelpLink i:nil="true" />
                  <InnerException i:nil="true" />
                  <Message>Unable to cast object of type 'OurNS.WebShop.Model.PlaceReservation' to type 'OurNS.WebShop.Model.OptionalPlaceReservation'.</Message>
                  <StackTrace>   at lambda_method(Closure , Object )
   at AutoMapper.Internal.PropertyGetter.GetValue(Object source)
   at AutoMapper.Internal.MemberGetter.Resolve(ResolutionResult source)
   at AutoMapper.PropertyMap.ResolveValue(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)</StackTrace>
                  <Type>System.InvalidCastException</Type>
                </InnerException>
                <Message>Trying to map OurNS.WebShop.Model.PlaceReservation to System.Decimal.
Using mapping configuration for OurNS.WebShop.Model.OptionalPlaceReservation to OurNS2.WebShop.WebServices.Contracts.OptionalPlaceReservation
Destination property: ReservationUnitPrice
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
                <StackTrace>   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)</StackTrace>
                <Type>AutoMapper.AutoMapperMappingException</Type>
              </InnerException>
              <Message>Trying to map OurNS.WebShop.Model.OptionalPlaceReservation to OurNS2.WebShop.WebServices.Contracts.OptionalPlaceReservation.
Using mapping configuration for OurNS.WebShop.Model.OptionalPlaceReservation to OurNS2.WebShop.WebServices.Contracts.OptionalPlaceReservation
Destination property: ValidatedBasketItem
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
              <StackTrace>   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)</StackTrace>
              <Type>AutoMapper.AutoMapperMappingException</Type>
            </InnerException>
            <Message>Trying to map OurNS.WebShop.Model.OptionalPlaceReservation to OurNS2.WebShop.WebServices.Contracts.OptionalPlaceReservation.
Using mapping configuration for OurNS.WebShop.Model.OptionalPlaceReservation to OurNS2.WebShop.WebServices.Contracts.OptionalPlaceReservation
Destination property: ValidatedBasketItem
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
            <StackTrace>   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)</StackTrace>
            <Type>AutoMapper.AutoMapperMappingException</Type>
          </InnerException>
          <Message>Trying to map OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult.
Using mapping configuration for OurNS.WebShop.Model.BasketItemValidationResult to OurNS2.WebShop.WebServices.Contracts.BasketItemValidationResult
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown.</Message>
          <StackTrace>   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
   at AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType)
   at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source)
   at OurNS.WebShop.WebServices.Server.Adapter.Map[TSource,TDestination](TSource source) in OurNS2.WebShop.WebServices.Server\Adapter.cs:line 1987
   at OurNS.WebShop.WebServices.Server.WebShopWebService.ValidateBasketItem(ValidateBasketItemRequest request) in OurNS2.WebShop.WebServices.Server\WebShopWebService.cs:line 526
   at SyncInvokeValidateBasketItem(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)</StackTrace>
          <Type>AutoMapper.AutoMapperMappingException</Type>
        </ExceptionDetail>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>
```

**Comment by bramdebouvere** [comment] 2015-05-26 13:58
I think we found the issue.
One of our models had the property ReservationUnitPrice (as below), that gets a value from the base class.

```c#
namespace OurNS.WebShop.Model
{
    public class OptionalPlaceReservation : PlaceReservation
    {
        public decimal ReservationUnitPrice
        {
            get { return base.UnitPrice; }
            set { base.UnitPrice = value; }
        }

        //...
    }
}
```

When the adapter was mapping this to the classes in the other namespace, i think it tried to convert the entire base class to a decimal, instead of just the UnitPrice on the base class.
After doing an ignore in our mapper (Adapter.cs) for ReservationUnitPrice, we have not seen this error return.

**Comment by jbogard** [comment] 2015-05-26 14:11
Ah can I close this then?

**Comment by bramdebouvere** [comment] 2015-05-26 19:22
Well it it actually looks like a bug in AutoMapper, but we worked around it now by not using any properties anymore that return a variable from the base class.

**Comment by lbargaoanu** [comment] 2015-06-22 12:40
I'm unable to reproduce. A simple case works:

        public class FromBase
        {
            public decimal BaseValue { get; set; }
        }

        public class From : FromBase
        {
            public decimal Value { get { return base.BaseValue; } set { base.BaseValue = value; } }
        }

        public class To
        {
            public decimal Value { get; set; }
        }

**Closed** 2015-09-10 03:15 UTC
