### ISSUE TITLE
Conditional Mappings Broken After 5.1.1

### ISSUE THREAD

**Issue by fgsahoward** [AutoMapper/AutoMapper#2088] opened 2017-04-25 15:05 UTC
It appears that the conditions in a conditional mapping are ignored (i.e. true or false the mapping is attempted) when mapping Nullable types. Note the tests both pass in version 5.1.1.

### Source/destination types

```csharp
public enum MyEnum
{
    Value1 = 1,
    Value2 = 2
}

public class SourceType
{
    public MyEnum? Value { get; set; }
}

public class DestinationType
{
    public MyEnum EnumValue { get; set; }
}
```

### Mapping configuration

```csharp
internal class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<SourceType, DestinationType>()
            .ForMember(dest => dest.EnumValue, opts =>
            {
                opts.Condition(src => src.Value.HasValue);
                opts.MapFrom(src => src.Value.Value);
            });
    }
}
```

### Tests

```csharp
[TestFixture]
public class AutomapperTests
{
    private IMapper _mapper;

    [SetUp]
    public void Setup()
    {
        Mapper.Initialize((cfg) => cfg.AddProfile(new MappingProfile()));

        _mapper = Mapper.Instance;
    }

    [Test]
    public void Map_GivenConditionalMappingWithConditionEvaluatingTrue_FaithfullyMapsValueToDestination()
    {
        var source = new SourceType() { Value = MyEnum.Value2 };

        var result = _mapper.Map<DestinationType>(source);

        Assert.That(result, Has.Property(nameof(DestinationType.EnumValue)).EqualTo(source.Value.Value));
    }

    [Test]
    public void Map_GivenConditionalMappingWithConditionEvaluatingFalse_FaithfullyIgnoresMappingTheValue()
    {
        var source = new SourceType() { Value = null };

        var result = _mapper.Map<DestinationType>(source);

        Assert.That(result, Has.Property(nameof(DestinationType.EnumValue)).EqualTo(default(MyEnum)));
    }
}
```

### Version: x.y.z

* 5.2.0
* 6.0.2

### Expected behavior

The test `Map_GivenConditionalMappingWithConditionEvaluatingFalse_FaithfullyIgnoresMappingTheValue` passes in as expected.

### Actual behavior

The test `Map_GivenConditionalMappingWithConditionEvaluatingFalse_FaithfullyIgnoresMappingTheValue` throws the exception below:

```
AutoMapper.AutoMapperMappingException : Error mapping types.

Mapping types:
SourceType -> DestinationType
FGS.Pump.Model.Tests.AutomapperTests+SourceType -> FGS.Pump.Model.Tests.AutomapperTests+DestinationType

Type Map configuration:
SourceType -> DestinationType
FGS.Pump.Model.Tests.AutomapperTests+SourceType -> FGS.Pump.Model.Tests.AutomapperTests+DestinationType

Property:
EnumValue
  ----> System.InvalidOperationException : Nullable object must have a value.
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at FGS.Pump.Model.Tests.AutomapperTests.Map_GivenConditionalMappingWithConditionEvaluatingFalse_FaithfullyMapsValueToDestination() in F:\repos\WebPump\FGS.Pump.Model.Tests\AutomapperTests.cs:line 35
--InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , Object , Object , ResolutionContext )
```

### Steps to reproduce

Run the tests as outlined above.

**Comment by lbargaoanu** [comment] 2017-04-25 15:08
Duplicate of #1723.
Try a PreCondition.

**Closed by lbargaoanu** 2017-04-25 15:08 UTC
