### ISSUE TITLE
AutoMapper fails to map class with non-default constructor

### ISSUE THREAD

**Issue by yellowpanda** [AutoMapper/AutoMapper#1456] opened 2016-07-06 06:46 UTC
When upgrading to version 5.0.0 (from nuget) I found this strange bug. 

I have two classes with one property each with different names. The target class has two constructors one default and one that take a value to fill the property. The parameter has the same name as the property. AutoMapper fail to map this this example. See unit test below. 

```
    [TestClass]
    public class AutoMapperBug
    {
        [TestMethod]
        public void Test()
        {
            Mapper.Initialize(config =>
            {
                config.CreateMap<ClassA, ClassB>().ForMember(dest => dest.PropertyB, opt => opt.MapFrom(src => src.PropertyA));
            });

            ClassA classA = new ClassA { PropertyA = "test" };
            ClassB classB = Mapper.Map<ClassB>(classA);
            Assert.AreEqual("test", classB.PropertyB);
        }
    }

    public class ClassA
    {
        public string PropertyA { get; set; }

    }

    public class ClassB
    {
        public ClassB()
        {
        }

        public ClassB(string propertyB)
        {
            PropertyB = propertyB;
        }

        public string PropertyB { get; set; }
    }
```

**Comment by tlycken** [comment] 2016-07-06 08:12
This is how you make that scenario work:

```c#
[TestClass]
    public class AutoMapperBug
    {
        [TestMethod]
        public void Test()
        {
            Mapper.Initialize(config =>
            {
                config.CreateMap<ClassA, ClassB>()
                    .ForCtorParam("propertyB", opt => opt.MapFrom(src => src.PropertyA));
            });

            Mapper.Configuration.AssertConfigurationIsValid();

            ClassA classA = new ClassA { PropertyA = "test" };
            ClassB classB = Mapper.Map<ClassB>(classA);
            Assert.AreEqual("test", classB.PropertyB);
        }

        public class ClassA
        {
            public string PropertyA { get; set; }
        }

        public class ClassB
        {
            public ClassB(string propertyB = null)
            {
                PropertyB = propertyB;
            }

            public string PropertyB { get; }
        }
    }
```

I agree, though, that it would be more intuitive if constructor mapping could resolve `ForMember` configuration too; after all, renaming the constructor parameter to match is not a breaking change to consuming code, so that's a reasonable requirement for this to work.

**Comment by lbargaoanu** [comment] 2016-07-06 08:38
I would say everything works as intended.

**Comment by jbogard** [comment] 2016-07-06 11:49
No, it should choose the no arg ctor if it can't map everything in the ctor
with params.

**Comment by lbargaoanu** [comment] 2016-07-06 11:51
@jbogard Yes, it does :)

**Comment by tlycken** [comment] 2016-07-06 12:32
@lbargaoanu But shouldn't it then try property mapping for the parameters that weren't mapped with the constructor? `ClassB.PropertyB` has a public setter.

**Comment by lbargaoanu** [comment] 2016-07-06 12:35
That was a bug, fixed in the MyGet build.

**Comment by lbargaoanu** [comment] 2016-07-06 12:43
Actually it was not merged yet. It's #1434.

**Comment by jbogard** [comment] 2016-07-06 16:35
Merged!

**Closed** 2016-07-06 19:27 UTC
Labels: Improvement
