### ISSUE TITLE
It is not possible to configure a mapping between an open generic type and a nongeneric or closed generic type

### ISSUE THREAD

**Issue by jnm2** [AutoMapper/AutoMapper#1112] opened 2016-02-15 20:48 UTC
The problem preventing open generic to nongeneric mappings (e.g. `Id<>` to `int`) and vice versa:
[`TypePair.GetOpenGenericTypePair`](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/TypePair.cs#L40) returns null unless both types are open generic types. Its only usage is in [`MapperConfiguration.FindClosedGenericTypeMapFor`](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/MapperConfiguration.cs#L349). [Repro for this problem.](https://gist.github.com/jnm2/2255b39cf0d205ae7132) [I think I found a solution to this problem.](https://gitter.im/AutoMapper/AutoMapper?at=56c230434dfe1fa71ffcf758)

To enable mapping an open generic to closed generic (e.g. `Id<>` to `Value<int>`) and vice versa, another lookup may be required.

**Comment by jbogard** [comment] 2016-02-16 14:28
Ah yes, I assumed no one would mix closed and open types in a single CreateMap. I think it makes sense to go open -> closed. Closed -> open doesn't seem to make any sense, though.

**Comment by jnm2** [comment] 2016-02-16 15:17
Open -> nongeneric and nongeneric -> open is a must for us. We are using `Id<DomainObject>` as a type annotation whose backing representation is an `int`. To serialize to DTOs, it'll have to get converted both directions.

As far as converting `Id<DomainObject>` (open) to `CustomValue<int>` (closed), I don't have a use case for that but I could see it happening. It's not that big of a step to go from serializing open types to `int` to open types to `Value<int>`. I mean after all, there is `Nullable<int>` and something else might follow that pattern.

**Comment by jbogard** [comment] 2016-02-16 15:20
Hmmm yeah that's true. There's no big reason why it's not there, it's just an assumption made from the feature developed.

**Comment by jnm2** [comment] 2016-02-16 15:47
Would you take a PR for v4 or is v5 looming on the horizon?

**Comment by jbogard** [comment] 2016-02-16 16:36
There's not a V4 branch, so this would be for V5.

I was originally going to wait for V5 to release when all of the DNX stuff got moved to the "dotnet" CLI and TFNs, but now that release date is "TBD". So I'm sticking with releasing V5 at the beginning of March.

**Comment by jnm2** [comment] 2016-02-16 20:11
Would you like a PR on this then?

**Comment by jbogard** [comment] 2016-02-16 20:19
Yeah of course!

**Comment by senritsu** [comment] 2016-02-23 18:10
Any timeline on that ? We have the same use case as @jnm2 and a probably related issue.

For a mapping of `Guid?` to `Id<T>` using a custom type converter, AutoMapper complains about a missing parameterless constructor for `Id<T>`, completely disregarding the custom converter.

**Comment by jnm2** [comment] 2016-02-23 20:43
I hit more complexity than I expected and I'm making sure I do the PR
justice. How soon do you need it?

**Comment by TylerCarlson1** [comment] 2016-02-23 21:35
Another way might be with conventions, but in order to do that we would need to add some kind of ITypeConverter generator based on the type maps. @jbogard would you want to assign an ITypeConverter generator per profile, or per convention?

**Comment by TylerCarlson1** [comment] 2016-02-23 21:39
Or even an AfterCreateMap function, where users can pass in an `Action<IMappingExpression>` and can do whatever they want including ConvertUsing.

**Comment by senritsu** [comment] 2016-02-24 05:40
@jnm2 As soon as possible. I am not 100% sure if the problem is the same though. I did some further testing and even if i leave out the `ITypeConverter` and use just map-specific settings like `NullOverride`s or `ForMember`+`MapsFrom` (and add a parameterless constructor so it doesn'nt complain about that missing) it still maps the `null` property to a `new Id<T>`. Not quite sure what is going on there.

**Comment by senritsu** [comment] 2016-02-24 06:42
I took a look at the sources, and the behaviour is quite explainable, but still undesired.

The `NullableSourceMapper` sees a null source value and continues to `MappingEngine.CreateObject`, which due to the fact our `Id<T>` implements `IEquatable<Id<T>>` continues with lines `78` and finally `87` to try to construct a new object, relegating the work to `DelegateFactory.CreateCtor` which can't find a suitable constructor and throws. 

The question is, why does the `MappingEngine` explicitely check for `AllowNullDestinationValues` in line `86`, but nowhere (that i can see at a glance) in the execution starting from `NullableSourceMapper` does it check the source for null, it just assumes that even though the source is `Nullable` the destination should never be null unless it is a string (`ObjectCreator.CreateObject(Type type)`, line `60`).

**Comment by jnm2** [comment] 2016-02-24 12:35
@senritsu I've got your use case [implemented](https://github.com/jnm2/AutoMapper/commit/2bb66b7215cfdc5fe755a95052a24a7a982e565c) (open generic <-> nongeneric). I'm working on open generic <-> closed generic.

**Comment by senritsu** [comment] 2016-02-24 12:40
@jnm2 That is very nice to hear. I have verified now that our issue is in fact the same you are fixing right now, including the open generic <-> closed generic case, so we will be cheering you on :+1:

**Comment by KevinDjordjevic** [comment] 2016-03-24 21:32
Any progress on this? I need to map from non-generic [HashTable] to open generic [IReadOnlyDictionary<TKey, TValue>].

Thanks!

**Comment by jnm2** [comment] 2016-03-24 21:36
Wow, is it a month already? I'll make it happen within a week.

**Comment by TylerCarlson1** [comment] 2016-03-25 20:52
If you add this to your profile it might work, for both too and from open/closed.
`AddConditionalObjectMapper().Where(OpenToClosed);`
with OpenToClosed defined as.
```
    private bool OpenToClosed(Type sourceType, Type destType)
    {
        var fromGeneric = sourceType.IsGenericType
                               && (sourceType.GetGenericTypeDefinition() != null) && !destType.IsGenericType;
        var toGeneric = sourceType.IsGenericType
                               && (sourceType.GetGenericTypeDefinition() != null) && !sourceType.IsGenericType;
        return fromGeneric || toGeneric;
    }
```

**Comment by jnm2** [comment] 2016-03-30 02:14
I spent an embarrassing amount of time figuring out how to deal with conflicting line endings. But all is well.

You should now be able to natively map between `HashTable` and `IReadOnlyDictionary<,>`, and between `Nullable<>` and anything.

**Comment by senritsu** [comment] 2016-03-30 04:38
That is very nice to hear, thanks a lot!

**Comment by KevinDjordjevic** [comment] 2016-04-04 15:06
Thanks for resolving this issue! Does anybody know when a new version is going to be pushed to NuGet?

**Comment by jbogard** [comment] 2016-04-04 15:29
That would be when RC2 of .NET core drops.

**Comment by jnm2** [comment] 2016-04-04 15:33
Which someone has had [set at April 15th](https://github.com/dotnet/corefx/milestones) on github even though @DamianEdwards insists it's too early to say anything. :laughing: Maybe we'll get a date [tomorrow](https://live.asp.net/)...

**Comment by jbogard** [comment] 2016-04-04 15:56
To be toooooootally transparent here, I'm waiting for .NET Core RC2 - not ASP.NET Core RC2. ASP.NET RC2 does not have a date yet (https://github.com/aspnet/Mvc/milestones). Yes this confused me too.

The reason why I'm waiting is for the new netstandard TFN to be available in VS and all the other tools.

**Comment by jnm2** [comment] 2016-04-04 16:09
Oh thanks, I didn't realize they were tracking differently. Though I'm confused again. NuGet 3.4 has RTMed with netstandard support and I thought [VS2015.2](https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx#nuget) had the tooling brought completely up to date with that release.

**Comment by jbogard** [comment] 2016-04-04 16:30
And the last part is that it needs to be on NuGet as a non-pre-release package. There's a deal with NuGet packages that if your package depends on a pre-release, then you have to mark as pre-release.

**Comment by KevinDjordjevic** [comment] 2016-04-14 20:45
I'm testing this out on AutoMapper 5.0.0-ci-1048, and I can't get it to work! It could be something simple/dumb on my end.

Context:

```
        public class Source
        {
            public Hashtable AProperty { get; set; }
        }

        public class Destination
        {
            public IReadOnlyDictionary<string, Element> AProperty { get; set; }
        }

        public class Element
        {

        }

        public class ReadonlyDictionaryConverter<TKey, TValue> :
            ITypeConverter<Hashtable, IReadOnlyDictionary<TKey, TValue>>
        {
            public IReadOnlyDictionary<TKey, TValue> Convert(Hashtable source, ResolutionContext context)
            {
                return source?.ToReadOnlyDictionary<TKey, TValue>();
            }
        }

        public static class CollectionAdapters
        {
            public static IReadOnlyDictionary<TKey, TValue> ToReadOnlyDictionary<TKey, TValue>(this Hashtable ht)
            {
                return ht == null
                    ? null
                    : new ReadOnlyDictionary<TKey, TValue>(
                        ht
                            .Cast<DictionaryEntry>()
                            .ToDictionary(e => (TKey) e.Key, e => (TValue) e.Value));
            }
        }
```

This does not work:

```
            new MapperConfiguration(cfg =>
            {
                cfg
                    .CreateMap(typeof (Hashtable), typeof (IReadOnlyDictionary<,>))
                    .ConvertUsing(typeof (ReadonlyDictionaryConverter<,>));
                cfg
                    .CreateMap<Source, Destination>();
            });
```

This does work:

```
            new MapperConfiguration(cfg =>
            {
                cfg
                    .CreateMap<Hashtable, IReadOnlyDictionary<string, Element>>()
                    .ConvertUsing<ReadonlyDictionaryConverter<string, Element>>();
                cfg
                    .CreateMap<Source, Destination>();
            });
```

I have tons of hashtables that need to be mapped, so I could save a lot of code by using the first MapperConfiguration.

**Comment by jnm2** [comment] 2016-04-14 22:18
@KevinDjordjevic Thanks for the sample, I'll repro it.

**Comment by jnm2** [comment] 2016-04-14 23:49
Found the problem.

@jbogard I need some input on this. [`GetTypeMap`](https://github.com/jnm2/AutoMapper/blob/develop/src/AutoMapper/MapperConfiguration.cs#L208) calls `CoveredByObjectMap` which returns true because it finds EnumerableMapper. Since it finds EnumerableMapper it calls it a day and doesn't look call `FindClosedGenericTypeMapFor`.

I don't understand the nuances of this bit: `(!CoveredByObjectMap(pair) ? FindConventionTypeMapFor(tp) ?? FindClosedGenericTypeMapFor(tp) : null)`.

Can I substitute `(!CoveredByObjectMap(pair) ? FindConventionTypeMapFor(tp) : null) ?? FindClosedGenericTypeMapFor(tp)`? That seems to solve the problem and the tests still pass.

**Comment by jnm2** [comment] 2016-04-15 00:21
There is another unrelated bug when the same converter type implements multiple instances of the ITypeConverter interface. The first closed type of the converter gets cached in the [returned closure](https://github.com/jnm2/AutoMapper/blob/develop/src/AutoMapper/TypeExtensions.cs#L28). Working on this as well.

**Comment by jnm2** [comment] 2016-04-15 00:47
Fixed both issues, @KevinDjordjevic's code is now running fine. Waiting for @jbogard's approval of the fix for the first issue.

**Comment by jnm2** [comment] 2016-04-15 01:28
Fixed both issues, @KevinDjordjevic's code is now running fine. Waiting for @jbogard's approval of the fix for the first issue. Preemptive PR at #1232.

**Closed** 2016-04-15 04:05 UTC
