### ISSUE TITLE
Having multiple IValueResolver implementations on a single class fails

### ISSUE THREAD

**Issue by NinoFloris** [AutoMapper/AutoMapper#2053] opened 2017-04-05 20:52 UTC
Automapper only considers the first Resolve method and then fails with 

```
System.InvalidOperationException : No coercion operator is defined between types 'X' and 'Y'
```

Fix is to take into account the types and resolve the correct method based on that

**Comment by lbargaoanu** [comment] 2017-04-06 05:25
https://github.com/AutoMapper/AutoMapper/blob/0f29418497958dd3eeff9a5145fd446fb0e3baf8/src/UnitTests/CustomMapping.cs#L21

**Comment by lbargaoanu** [comment] 2017-04-06 05:35
Duplicate of https://github.com/AutoMapper/AutoMapper/issues/1887.

**Closed by lbargaoanu** 2017-04-06 05:35 UTC
