### ISSUE TITLE
"opts.Condition" not being honoured when calling Map<TSource, TDest>()

### ISSUE THREAD

**Issue by mrpmorris** [AutoMapper/AutoMapper#2472] opened 2017-12-28 11:29 UTC
### Source/destination types

```csharp
    public class SomeState
    {
        public Guid Id { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
    }
```

### Mapping configuration

```csharp
    public class AutoMapperProfile : Profile
    {
        public AutoMapperProfile()
        {
            CreateMap<SomeState, SomeState>();
        }
    }
```

### Expected behavior
Condition code should be executed (exception thrown)

### Actual behavior
Condition code was not executed (exception not thrown)

### Steps to reproduce

```csharp
    [TestClass]
    public class UnitTest1
    {
        private Guid Id = Guid.NewGuid();
        private IMapper AutoMapper;

        [TestMethod]
        public void TestMethod1()
        {
            var stateWithGivenName = new SomeState { Id = Id, GivenName = "X" };
            var stateWithFamilyName = new SomeState { Id = Id, FamilyName = "Y" };

            Assert.ThrowsException<InvalidOperationException>(() =>
            {
                SomeState mergedState = AutoMapper.Map<SomeState, SomeState>(stateWithGivenName, stateWithFamilyName,
                    cfg => cfg.ConfigureMap()
                    .ForAllMembers(opts => opts.Condition((source, target, sourceValue, targetValue) =>
                    {
                        throw new InvalidOperationException();
                    })));
            });
        }

        public UnitTest1()
        {
            var mapperConfig = new MapperConfiguration(cfg => cfg.AddProfile<AutoMapperProfile>());
            AutoMapper = mapperConfig.CreateMapper();
        }
    }
```

**Comment by lbargaoanu** [comment] 2017-12-28 12:13
Duplicate of #2453.

**Closed by lbargaoanu** 2017-12-28 12:13 UTC
