### ISSUE TITLE
Add IsInitialized static property

### ISSUE THREAD

**Issue by jez9999** [AutoMapper/AutoMapper#2716] opened 2018-07-13 13:01 UTC
To avoid having to get (and catch) an exception when I initialize the mapper in a class constructor, why on Earth can't I just say this:

```
if (!Mapper.IsInitialized) {
    Mapper.Initialize(...)
}
```

Surely it would be easy to add this property.

**Comment by lbargaoanu** [comment] 2018-07-13 13:08
Duplicate of #2497.

**Closed by lbargaoanu** 2018-07-13 13:08 UTC
