### ISSUE TITLE
Mappings with the same type as the parent (Not self referencing) are ignored when Projecting. Work when Mapping.

### ISSUE THREAD

**Issue by douglasg14b** [AutoMapper/AutoMapper#3195] opened 2019-08-16 21:32 UTC
## Source/destination types

**Source:**

```cs
    public class Attribute
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int? RequiredAttributeId { get;set; } 

        public Attribute RequiredAttribute { get;set; }

        public List<AttributeValue> Values { get; set; }
    }
```

**Destination:**

```cs
    public class AttributeDto
    {
        public int Id { get; set; }
        public string Name { get;set; }

        public int? RequiredAttributeId { get;set; }

        public AttributeDto RequiredAttribute { get; set; }

        public List<AttributeValueDto> Values { get; set; }
    }
```

### Mapping configuration

Note: `MaxDepth()` has no effect on this issue.

```csharp
            config.CreateMap<Attribute, AttributeDto>();
            config.CreateMap<AttributeValue, AttributeValueDto>()
```

### Expected behavior

That the property `RequiredAttribute` would be mapped when using `ProjectTo<AttributeDto>`. Just like if I loaded the entity and did a `IMapper.Map<AttributeDto>()` call.

### Actual behavior

`RequiredAttribute` is always null when using projections. 

### Steps to reproduce

Note: I did think maybe this is `MaxDepth()` related, but no matter what `MaxDepth()`  is set to, this still doesn't project. This is also not self-referencing as `RequiredAttribute` is a different entity.

```cs
            // Attribute Entity has RequiredAttribute filled in
            Attribute attribute = _context.Attributes
                .Where(x => x.Id == id)
                .Include(x => x.Values)
                    .ThenInclude(x => x.ChildValues)
                .Include(x => x.RequiredAttribute)
                .SingleOrDefault();

            // Mapped AttributeDto has RequiredAttribute filled in
            AttributeDto  attributeMapped = _defaultMapper.Map<AttributeDto>(attributetest);

             // Projected AttributeDto has null RequiredAttribute 
            AttributeDto  attributeDto = _context.Attributes
                .Where(x => x.Id == id)
                .Include(x => x.Values)
                    .ThenInclude(x => x.ChildValues)
                .Include(x => x.RequiredAttribute)
                .ProjectTo<AttributeDto>()
                .SingleOrDefault();

            // Projected AttributeDto with explicit projection has null RequiredAttribute 
            AttributeDto attributeDtoExplicit = _context.Attributes
                .Where(x => x.Id == id)
                .Include(x => x.Values)
                    .ThenInclude(x => x.ChildValues)
                .Include(x => x.RequiredAttribute)
                .ProjectTo<AttributeDto>(x => x.RequiredAttribute)
                .SingleOrDefault();
```

**Comment by lbargaoanu** [comment] 2019-08-17 05:40
Duplicate of #2171.

**Closed by lbargaoanu** 2019-08-17 05:40 UTC
Labels: Question

**Comment by douglasg14b** [comment] 2019-08-17 21:38
@lbargaoanu  Can you please, succinctly, explain what is wrong here if you believe this to be a question? How is this recursive? I specifically stated that the child entity is **NOT** self-referencing.

Why does this map, but not project?

The linked issue (that this is a duplicate of?) did not have a resolution, as the poster pointed out that ` I skipped using AutoMapper in this scenario and created a EF query that satisfied my needs in this.`.

**Comment by lbargaoanu** [comment] 2019-08-18 04:10
In one form or another, this question has been discussed many times before, here and on SO. We don't have another answer. If you need further assistance, please ask on SO.

**Comment by jbogard** [comment] 2019-08-18 13:33
Your `Attribute` and corresponding DTO are self referencing through the `RequiredAttribute` property.


Try writing this projection without AutoMapper using only Select with LINQ.

**Comment by douglasg14b** [comment] 2019-08-19 18:06
@jbogard  Thanks, I'm just trying to understand the problem as the linked issue doesn't succinctly describe it, and that issue is locked and further discussion isn't possible there.

If I understand this correctly, a child entity of the same type, even if it's not the same entity (ie. by Id), is still self referencing? Is the MaxDepth config not for this then?
