### ISSUE TITLE
Updating child property of existing EF6 entity creates new child property

### ISSUE THREAD

**Issue by michaelmsm89** [AutoMapper/AutoMapper#1560] opened 2016-07-23 22:37 UTC
Since upgrading to Automapper 5, when updating an Entity Framework 6 entity with a child property, the child property is added as a new record to the database rather than being updated.
Downgrading to 4.2.1 fixes the issue. 

I have an entity Customer

```
public class Customer {
    public string Name { get; set; }
    public virtual CustomerSettings Settings { get; set; }
}

public class CustomerSettings {
    public long Id { get; set; }
    public string SettingString { get; set; }
}
```

I then have data transfer objects
```
public class UpdateCustomerRequest {
    public string Name { get; set; }
    public UpdateCustomerSettingsRequest Settings { get; set; }
}

public class UpdateCustomerSettingsRequest {
    public string SettingString { get; set; }
}
```

I have the following maps:
```
CreateMap<UpdateCustomerRequest, Customer>();
CreateMap<UpdateCustomerSettingsRequest , CustomerSettings>();
```

I then pull out an existing Customer from the database along with their existing settings and update:

```
var updateCustomerRequest = new UpdateCustomerRequest { Settings = new UpdateCustomerSettingsRequest { SettingsString = "foo"}  }
var existingCustomer = DataContext.Customers.Include(c => c.Settings).First(c => c.Id == customerId);

Mapper.Map(updateCustomerRequest, existingCustomer);
DataContext.SaveChanges();
```

**Outcome:**
Using Automapper 4.2.1, the existingCustomer correctly has their SettingString updated to the SettingsString in the UpdateCustomerSettingsRequest. 

Using Automapper 5.0.2, the SettingString is updated, but the CustomerSettings.Id is set to 0 rather than keeping it's existing Id of 1. EF then adds a new record to the CustomerSettings table, rather than updating the existing record.

**Comment by lbargaoanu** [comment] 2016-07-24 07:19
Duplicate of #1486. You can close the issue.

**Closed** 2016-07-24 08:15 UTC
