### ISSUE TITLE
Incorrect mapping chosen when immediate source type is not mapped.

### ISSUE THREAD

**Issue by MadillJ** [AutoMapper/AutoMapper#893] opened 2015-09-15 17:25 UTC
This issue requires a fairly specific set of circumstances for it to occur.

First the source object needs to be an instance of a class that derives the type that is mapped, in my case it is an Active Record Proxy.

Second there needs to be two possible destination types one of which derives from the other.

Finally the source needs to be first mapped to the base destination type, the issue then occurs when mapping to the derived destination type, the type map that is retrieved is the one that was cached on the first mapping which results in an invalid cast.

The problem appears to be in ConfigurationStore.cs between the results of GetRelatedTypePairs() and the select that is performed in ResolveTypeMap(TypePair typePair).  My first guess at the fix is to not include the base class of the destination type as a possible value as I cannot think of a case where that would be valid.

SO question that lead to this issue: http://stackoverflow.com/questions/32574749/auto-mapper-is-failing-to-map-a-castle-active-record-proxy-to-multiple-destinati

**Comment by lbargaoanu** [comment] 2015-09-15 18:20
Probably duplicate of #842.

**Comment by MadillJ** [comment] 2015-09-15 19:07
I'm not sure it is as I was unable to resolve it with any variation of Include.

**Comment by TylerCarlson1** [comment] 2015-09-15 21:10
It's a duplicate of #842 and #887.  It was resolved in 3.3.1 and with 4.0.4 it broke.

**Closed** 2015-09-21 12:54 UTC
