### ISSUE TITLE
Mappings to same type parent object ignored

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper#3138] opened 2019-06-20 10:40 UTC
There is a full repro case for this in the repository at https://github.com/NetTecture/Automapper.Bugs.ParentMapping/tree/master/Tests.ProjectTo with an easy to execute unit test.

In short:

There are 2 target classes (ApiModel namespace):

    public class Event
    {

        public Int32 Id { get; set; }

        public Guid Identity { get; set; }

        public Event Parent { get; set; }

        public Result Result { get; set; }

    }

and 

    public class Result
    {

        public Int32 Id { get; set; }

        public Guid Identity { get; set; }

    }

There are mappings defined for this (Mappings namespace):

            CreateMap<DataModel.TEvent, ApiModel.Event>()
                   .ForMember(d => d.Identity, o => o.MapFrom(s => s.Identity))
                   .ForMember(d => d.Id, o => o.MapFrom(s => s.Id))
                   .ForMember(d => d.Parent, o => { o.MapFrom(s => s.Parent); o.ExplicitExpansion(); })
                   .ForMember(d => d.Result, o => { o.MapFrom(s => s.Result); o.ExplicitExpansion(); })
                   .ForAllOtherMembers(o => o.Ignore())
                    ;

            CreateMap<DataModel.TResult, ApiModel.Result>()
               .ForMember(d => d.Identity, o => o.MapFrom(s => s.Identity))
               .ForMember(d => d.Id, o => o.MapFrom(s => s.Id))
               .ForAllOtherMembers(o => o.Ignore())
                ;

DataModel has a fake EF Core repository with both classes (TEvent and TResult) mapped out enough for this example to work.

There is au nit test in SelfMappings.

The following code is used to get access to the generated expression tree:

                var query = repository.TEvent
                    .ProjectTo<ApiModel.Event>(new Dictionary<String, Object>(), "Parent", "Result")
                    ;
                var expression = query.Expression;

The resulting expression looks like this:

```
.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Tests.ProjectTo.DataModel.TEvent]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Tests.ProjectTo.DataModel.TEvent]),
    '(.Lambda #Lambda1<System.Func`2[Tests.ProjectTo.DataModel.TEvent,Tests.ProjectTo.ApiModel.Event]>))

.Lambda #Lambda1<System.Func`2[Tests.ProjectTo.DataModel.TEvent,Tests.ProjectTo.ApiModel.Event]>(Tests.ProjectTo.DataModel.TEvent $dtoTEvent)
{
    .New Tests.ProjectTo.ApiModel.Event(){
        Id = $dtoTEvent.Id,
        Identity = $dtoTEvent.Identity,
        Result = .If ($dtoTEvent.Result == null) {
            null
        } .Else {
            .New Tests.ProjectTo.ApiModel.Result(){
                Id = ($dtoTEvent.Result).Id,
                Identity = ($dtoTEvent.Result).Identity
            }
        }
    }
}
```

As can clearly be seen, it maps Id and Identity as data properties correctly.

If then maps the "Result" to a subclass of type Result, as is define.

It totally ignores the mapping for the property "Parent" property although they are following the exactly same type decition and an earlier test of the configuration (Mapper.AssertConfigurationIsValid()) shows no error.

There is a unit test in Self-Mappings with the full code ready to execute, all required is the a current .NET Core 2.2 SDK.

**Comment by vietlp** [comment] 2019-07-31 07:22
I'm facing same problem. Any update?

**Comment by lbargaoanu** [comment] 2019-07-31 07:25
Duplicate of #2171.

**Closed by lbargaoanu** 2019-07-31 07:25 UTC

**Comment by NetTecture** [comment] 2019-07-31 08:37
It would be funny as duplicate if it would not still be a bug - i.e. the solution given in the link seems simply not to work.

I have simplified the above example.

* Removed EF COre refrerence, now working from a manually generated in memory array:

            var data = new TEvent[]
            {
                new TEvent()
                {
                    Parent = new TEvent(),
                    Result = new TResult(),
                },

                new TEvent()
                {
                    Parent = new TEvent(),
                    Result = new TResult(),
                }
            };

* Added MaxDepth to the profile for Event (the parent object).

            CreateMap<DataModel.TEvent, ApiModel.Event>()
                .MaxDepth(3)
                .ForMember(d => d.Identity, o => o.MapFrom(s => s.Identity))
                .ForMember(d => d.Id, o => o.MapFrom(s => s.Id))
                .ForMember(d => d.Parent, o => { o.MapFrom(s => s.Parent); o.ExplicitExpansion(); })
                .ForMember(d => d.Result, o => { o.MapFrom(s => s.Result); o.ExplicitExpansion(); })
                .ForAllOtherMembers(o => o.Ignore())
                ;

* Adjusted the test to throw an exception is the parent mapping is null.

Voila, exception hits. The generated code still ignores the exception DESPITE the MaxDepth being set.

The changed test has been uploaded to the repository at 

https://github.com/NetTecture/Automapper.Bugs.ParentMapping/tree/master/Tests.ProjectTo
