### ISSUE TITLE
AutoMapperConfigurationException does not report where the bug is

### ISSUE THREAD

**Issue by rudolfdobias** [AutoMapper/AutoMapper#1997] opened 2017-03-11 21:29 UTC
Hello,

Somewhere in my model I have a bug (inconsistent destination type). The model counts dozens of classes and mappings but the exception does not say where the bug is located. Manual search would take hours since it could be anywhere. Is this bug or feature? Or am I doing something wrong? 

The exception from configuration validation:

```Unhandled Exception: System.AggregateException: One or more errors occurred. (The following property on System.Decimal cannot be mapped: 
	
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type System.Decimal.
Context:
	Mapping from type Kapacity.Models.Price to System.Decimal
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.) (The following property on System.Decimal cannot be mapped: 
	
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type System.Decimal.
Context:
	Mapping from type Kapacity.Models.Price to System.Decimal
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.) ---> AutoMapper.AutoMapperConfigurationException: The following property on System.Decimal cannot be mapped: 
	
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type System.Decimal.
Context:
	Mapping from type Kapacity.Models.Price to System.Decimal
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.

...
```

Version: 5.2.0
Platform: .NET Core 1.1

Thanks

**Comment by TylerCarlson1** [comment] 2017-03-11 22:01
The exception says price to decimal is the problem.
If you don't have a mapper for it then make one and it should work.

**Comment by rudolfdobias** [comment] 2017-03-11 22:08
That's right but this is a mistake. No one wants to convert price to
decimal, I just want to fix the destination type. But now I don't know
where in all of the models this mismatch is.

Dne 11. 3. 2017 11:02 odpoledne napsal uživatel "Tyler Carlson" <
notifications@github.com>:

The exception says price to decimal is the problem.
If you don't have a mapper for it then make one and it should work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AutoMapper/AutoMapper/issues/1997#issuecomment-285903529>,
or mute the thread

**Comment by TylerCarlson1** [comment] 2017-03-11 22:11
`cfg.ForAllPropertyMaps(pm => pm.SourceType == typeof(Price) && pm.DestinationPropertyType == typeof(decimal), (pm, e) => e.Ignore());` or something to that extent

**Comment by rudolfdobias** [comment] 2017-03-11 22:24
That's still not what I meant. That's not my problem. Ignoring it will not help in any way. 

The exception says "...or modify the destination type to xxx" and that's what I have to do.
But without the location of the error, should I go through 50 entities and compare them manually where the bad type is? Hope not.

Putting it straight - the exception should say where the problem is.

**Comment by rudolfdobias** [comment] 2017-03-12 03:39
For understanding - let's have two models:

```
public class EntityA{
   public TypeA Something {get;set;}
}

public class ViewModelA {
  public TypeB Something {get;set} 
}
```

I declare mapping between these two models forgetting that the `Something` field have different types in the models:

```
CreateMap<EntityA, ViewModelA>();
```

Now the error is obvious - TypeA cannot be mapped to TypeB implicitly.
But I don't want to ignore it and also don't want to define conversion between TypeA and TypeB (becasue it may not be even possible).

Now imagine there are hundreds of models and dozens of mappings and I make this error only in one of them:

```
CreateMap<EntityA, ViewModelA>();
...
CreateMap<EntityM6, ViewModelM6>(); <-- there is an error because I've made an typo in field type
...
CreateMap<EntityZ9, ViewModelZ9>();
```

and the exceptions says this:

```
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type TypeB.
Context:
	Mapping from type TypeA to TypeB
```

Right now I have no idea in which of the 52 classes I've made the mistake.
IMHO, the exception should say something like:

```
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
Mapping from TypeA to TypeB is not defined. 
Occured while mapping MyProject.Models.EntityM6 to MyProject.ViewModels.ViewModelM6
Add custom mapping expresion, ignore ...(etc)
```

Maybe I'm missing something...

**Comment by jbogard** [comment] 2017-03-12 04:12
The exception contexts should tell you where the issue is, do you have any
other stack trace? or gist?

**Comment by lbargaoanu** [comment] 2017-03-12 06:07
Duplicate of https://github.com/AutoMapper/AutoMapper/issues/1908. 
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Closed by lbargaoanu** 2017-03-12 06:07 UTC
