### ISSUE TITLE
Ignoring nullable enum does not work on Automapper 5.2

### ISSUE THREAD

**Issue by Freakazoid182** [AutoMapper/AutoMapper#1912] opened 2017-01-17 10:23 UTC
Using the following configuration:
```
config.CreateMap<UpdateNoteDTO, Note>()
.ForAllMembers(p => p.Condition((source, destination, sourceMember, destMember) => sourceMember != null));
```

and following models

```
public class UpdateNoteDTO
{
   public string Content { get; set; }

   public ContactType? ContactType { get; set; }
}
```
```
public class Note
{
   public string Content {get; set;}
   public ContactType ContactType { get; set; }
}
```
```
public enum ContactType : byte
{
        None,
        Phone,
        Email
}

```

When mapping the `UpdateNoteDTO` to `Note`, with `UpdateNoteDTO.ContactType = null`, `Note.ContactType` always get set to `None`, also when the original `Note.ContactType` has another value. Somehow Automapper sets the enum to the default value. This does not happen for non-enum values.  When setting `UpdateNoteDTO.Content = null` the mapping of this member will be ignored.

**Comment by lbargaoanu** [comment] 2017-01-17 10:38
There are workarounds. See https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-265670132 and the discussion there.

**Comment by lbargaoanu** [comment] 2017-01-23 10:42
Duplicate of #1723.

**Closed by lbargaoanu** 2017-01-23 10:42 UTC
