### ISSUE TITLE
InvalidCastException when using ConvertUsing

### ISSUE THREAD

**Issue by mkoppanen** [AutoMapper/AutoMapper#3472] opened 2020-07-21 13:20 UTC
Hello,

I am quite new to C# so this bug might be my misunderstanding of how AutoMapper works. However, the example below fails an unit test, which I would expect to succeed.

### Source/destination types

```csharp
var source = "2020-01-01T10:10:00Z";
```

### Mapping configuration

```csharp
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<string, DateTime>()
                    .ConvertUsing(source => DateTime.Parse(source, null, System.Globalization.DateTimeStyles.RoundtripKind));
            });
            var mapper = new Mapper(configuration);
```

### Expected behavior

I expected the mapping to succeed. I would not expect there to be different between these calls

### Actual behavior

System.InvalidCastException : Unable to cast object of type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,System.DateTime]' ...

System.InvalidCastException : Unable to cast object of type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,System.DateTime]' to type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,System.Object]'.
   at AutoMapper.MapperConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest mapRequest)
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map(Object source, Object destination, Type sourceType, Type destinationType)
   at AutoMapper.Mapper.Map(Object source, Type sourceType, Type destinationType)
   at Medsol.StandardApi.Tests.Tests.Mapping.DateTimeMappingTests.Test_Runtime_Mapping() in <redacted>

### Steps to reproduce

```csharp
        [Fact]
        public void Test_Runtime_Mapping()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<string, DateTime>()
                    .ConvertUsing(source => DateTime.Parse(source, null, System.Globalization.DateTimeStyles.RoundtripKind));
            });
            
            var mapper = new Mapper(configuration);
            
            var value = "2020-01-01T10:10:00Z";

            // fails
            mapper.Map(
                value,
                value.GetType(),
                DateTime.UtcNow.GetType()
            );

            // fails
            mapper.Map(
                value,
                value.GetType(),
                typeof(DateTime)
            );

           // succeeds
          mapper.Map<DateTime>(value);
            
        }
```

**Comment by lbargaoanu** [comment] 2020-07-21 13:28
Duplicate of #3455. You already found the workaround.

**Closed by lbargaoanu** 2020-07-21 13:28 UTC
