### ISSUE TITLE
Enums mapping not work in GetQuery 

### ISSUE THREAD

**Issue by petrkasnal** [AutoMapper/AutoMapper#4299] opened 2023-06-07 08:32 UTC
Hi,

i use odata automapper extension.

`var items = (_repository.GetAll().GetQuery(_mapper, request.Query)).ToList();`
Everything working fine, but when i add enum to source and destination it not working. I give this error. I have Mapper on enums.

'Unable to create a map expression from Bom.CheckStateType (System.Nullable1[StateType]) to Nullable1.StateType (System.Nullable`1[StateType])'

**Comment by lbargaoanu** [comment] 2023-06-07 08:37
Duplicate of https://github.com/AutoMapper/AutoMapper.Extensions.OData/issues/181

**Closed by lbargaoanu** 2023-06-07 08:37 UTC
