### ISSUE TITLE
Mapping Com Object: Missing type map configuration or unsupported mapping.

### ISSUE THREAD

**Issue by StefanSchoof** [AutoMapper/AutoMapper#768] opened 2015-07-06 13:05 UTC
I try to map a Interop Com Object to a .Net Object and getting a exception:
```
Missing type map configuration or unsupported mapping.

Mapping types:
ProjectTimeRecord -> TimeRecord
ComTimeRecording.ProjectTimeRecord -> AutoMapperTest.TimeRecord

Destination path:
TimeRecord

Source value:
System.__ComObject
```
The Interop library is a private dll, I cloud not share. I write minimal code to reproduce:

```
    class TimeRecord
    {
        public int Id { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            ProjectTimeRecord projectTimeRecord = GetRecord();

            Console.WriteLine(projectTimeRecord.GetType());
            // Output: "System.__ComObjects"

            Mapper.CreateMap<ProjectTimeRecord, TimeRecord>();

            // Exception in next line
            TimeRecord record = Mapper.Map<ProjectTimeRecord, TimeRecord>(projectTimeRecord);
            Console.WriteLine(record.Id);
        }
    }
```

I use VS2015 RC, .NET 4.6 RC and  AutoMapper 4.0.0-ci1061. On StackOverflow is a [question with the same exception] (http://stackoverflow.com/questions/28862567/map-com-object-with-automapper)

**Comment by jbogard** [comment] 2015-07-06 13:09
I've never attempted to use COM and AutoMapper. How could I reproduce this locally?

**Comment by StefanSchoof** [comment] 2015-07-06 13:26
A fast way (if you have Outlook): create a console application, add Microsoft.Office.Interop.Outlook (15.0.0.0), start Outlook and insert.
```
using AutoMapper;
using Microsoft.Office.Interop.Outlook;
using System;
using System.Runtime.InteropServices;

namespace AutoMapperTest
{
    class LocalMail
    {
        public string BCC { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Application application = Marshal.GetActiveObject("Outlook.Application") as Application;
            MailItem mail = application.CreateItem(OlItemType.olMailItem);

            Console.WriteLine(mail.GetType());
            // Output: "System.__ComObjects"

            Mapper.CreateMap<MailItem, LocalMail>();
            LocalMail localMail = Mapper.Map<MailItem, LocalMail>(mail);
            Console.WriteLine(localMail.BCC);
        }
    }
}
```

**Comment by lbargaoanu** [comment] 2015-07-08 13:11
I guess [here](https://github.com/AutoMapper/AutoMapper/blob/e144e8a3595e923265cfa90b9387bc3c1ce08947/src/AutoMapper/ConfigurationStore.cs#L343) __ComObject should be special cased.

**Comment by lbargaoanu** [comment] 2015-07-08 13:45
Perhaps solving #724 would solve this one too.

**Comment by jbogard** [comment] 2015-09-10 03:20
@StefanSchoof is this one fixed with 4.0?

**Comment by StefanSchoof** [comment] 2015-09-10 07:51
Just tested with 4.0.4 and I got the same Message.

**Comment by lbargaoanu** [comment] 2015-10-29 15:20
As a workaround you can use only the COM class implementing the interface, or just cast when mapping. The idea is that the object passed to map has to return a specific type from GetType, not just __ComObject.

**Comment by lbargaoanu** [comment] 2015-10-29 15:25
@jbogard If you're against special casing COM objects somehow than I guess this can be closed. The workaround seems to work.

**Comment by jbogard** [comment] 2016-01-18 15:49
Closing!

**Closed by jbogard** 2016-01-18 15:49 UTC

**Comment by steveoh** [comment] 2016-06-08 21:54
Can you give an example of the work around. I don't quite follow

 > you can use only the COM class implementing the interface or just cast when mapping.

**Comment by lbargaoanu** [comment] 2016-06-09 08:44
This will output ApplicationClass, not __ComObject. And the mapping will work.

            var _x = (Microsoft.Office.Interop.Excel._Application) new Microsoft.Office.Interop.Excel.ApplicationClass();
            Console.WriteLine(_x);
            var _result = _mapper.Map<App>(_x);

**Comment by steveoh** [comment] 2016-06-09 14:09
Ok. The com library I am working with, when I try to use the class, throws an error that it is not embeddable so that option does not work for me. I'd like to see the __ComOobject special case like you mentioned above and what that might look like so GetType isn't always __ComObject.

**Comment by lbargaoanu** [comment] 2016-06-09 14:14
You can also mark the reference not embeddable. Or write your own ObjectMapper for __ComObject.

**Comment by lbargaoanu** [comment] 2016-06-14 14:02
Apparently a generic COM object mapper that covers this case is not trivial. [Here](https://gist.github.com/lbargaoanu/857125af403e0a9abe5c135cd462d8df) is my attempt that works with the MyGet build. Improvements are welcome :)

**Comment by vuchl** [comment] 2016-07-05 14:37
I have the same problem but with GroupWise ComObjects. @lbargaoanu what  are yor usings in your ComObjectMapper file?

**Comment by kbkk** [comment] 2017-07-10 08:26
Here's an implementation for AutoMapper 6:
https://gist.github.com/kbkk/39e9c7125c6b52ab86692b5f3e10408a

**Comment by alexvilper** [comment] 2017-10-19 20:05
Hi Guys,

Is there anything else that needs to be done for AssertConfigurationIsValid() stop throwing errors during bootstrap?

I have implemented the ComObjectMapper, but I am still getting the error:

> Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
=================================================================================


My Mapper.Initialize looks like this:
`            Mapper.Initialize(cfg =>
                {
                    Reflection.FindClassesImplementing<Profile>("test", false)
                        .ForEach(profileType => cfg.AddProfile(Activator.CreateInstance(profileType) as Profile));
                    cfg.Mappers.Add(new ComObjectMapper());
                });
            Mapper.AssertConfigurationIsValid();
`

And my map (_source & destination names are fake here_):

`    public class KsMaps : Profile
    {
        public KsMaps()
        {
            CreateMap<sourceInteropInterface, destinationClass>()
                ;
        }
    }
`
Thanks!

Alex
