### ISSUE TITLE
Mapping to the same type returns source object (4.2.1 version)

### ISSUE THREAD

**Issue by sdm-kz** [AutoMapper/AutoMapper#1215] opened 2016-04-01 10:26 UTC
When using dynamic mapping (`CreateMissingTypeMaps  = true`) to clone object (the same source and destination types) the Map() method  returns the same source object.

The code sample:

```
void Main()
{
	var config = new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = true);
	config.AssertConfigurationIsValid();
	var mapper = config.CreateMapper();

	var foo1 = new Foo { Text = "111" };
	var foo2 = mapper.Map<Foo>(foo1);
	
	Console.WriteLine(foo1 == foo2); // Outputs True
}

class Foo
{
	public string Text {get;set;}
}
```

If create map manually:

```
	var config = new MapperConfiguration(cfg => cfg.CreateMap<Foo, Foo>());
```

then all is fine.

**Comment by lbargaoanu** [comment] 2016-04-01 10:31
That's by design.

**Comment by sdm-kz** [comment] 2016-04-01 10:55
Ok, clear

**Comment by lbargaoanu** [comment] 2016-04-01 11:27
You can close the issue.

**Closed** 2016-04-01 11:31 UTC

**Comment by jbogard** [comment] 2016-04-01 13:10
@sdm-kz the design is if AutoMapper sees two types, and they're assignable to each other (int -> int, string -> string etc) it just assigns them.

That is, unless you do one of two things - create a map between the types with CreateMap, or a custom IObjectMapper (rarer). You've configured to create missing type maps, but in this case of cloning, AutoMapper just sees two types that are the same and can be assigned to each other. So it does.

**Comment by sdm-kz** [comment] 2016-04-01 13:36
@jbogard, thanks for the explanation. I was a bit confused with the Map method's summary "Execute a mapping from the source object to **a new** destination object", so I thought it should create new object always
