### ISSUE TITLE
IgnoreAllPropertiesWithAnInaccessibleSetter doesn't work with a base class

### ISSUE THREAD

**Issue by kakone** [AutoMapper/AutoMapper#2839] opened 2018-10-19 18:23 UTC
Hello,

I have a DTO that inherit a base class with a property with a private setter. In this case, the IgnoreAllPropertiesWithAnInaccessibleSetter configuration method doesn't work well: the base class property is not ignored and a AutoMapperConfigurationException is throwed on AssertConfigurationIsValid method call.

### Source/destination types

```csharp
public class Test
{
  public string Property { get; set; }
}

public abstract class TestDTOBase
{
  public string PrivateSetterProperty { get; private set; }
}

public class TestDTO : TestDTOBase
{
  public string Property { get; set; }
}
```

### Mapping configuration

```csharp
public class TestProfile : Profile
{
  public TestProfile()
  {
    CreateMap<Test, TestDTO>();
  }
}

var config = new MapperConfiguration(cfg =>
{
  cfg.CreateMissingTypeMaps = false;
  cfg.ForAllMaps((tm, me) => me.IgnoreAllPropertiesWithAnInaccessibleSetter());
  cfg.AddProfile<TestProfile>();
});
config.AssertConfigurationIsValid(); // throws exception : Unmapped properties: PrivateSetterProperty
```

### Version: 7.0.1

**Comment by lbargaoanu** [comment] 2018-10-19 18:41
Duplicate of #2740

**Closed by lbargaoanu** 2018-10-19 18:41 UTC
