### ISSUE TITLE
Pre-calculate property map mapping plans

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1156] opened 2016-03-02 13:59 UTC
As described in comment in #1155 to build out not just a `Func<ResolutionContext, object>` to resolve a value, but build out an `Action<ResolutionContext, object>` that actually performs the LHS-RHS mapping for a property.

Eventually these could be pulled together for an action on the TypeMap, but this starts somewhere.

I don't think we'll ever get to a single expression per TypeMap, we'd have to give up runtime features. But at least could get to individual property maps.

One thing that would certainly help here is making IValueResolver be generic, so that value resolvers could inform the configuration what types will be returned. We can also use the type maps' polymorphic information to see if you've done IncludeBase or Include and fallback to runtime types based on that.

@lbargaoanu @TylerCarlson1 thoughts?

**Comment by lbargaoanu** [comment] 2016-03-02 14:19
Sounds good :) Might be more difficult to debug though.

**Comment by jbogard** [comment] 2016-03-02 14:49
The way I think we can help that is only do the 99% cases and fall back to
regular mapping when I can't assign.

**Comment by TylerCarlson1** [comment] 2016-03-02 21:33
So what you want to do is take the property resolving to go from a cascading call of ResolveValues to merge into a single ResolveValues function?  Or do you want each ResolveValue functions to return a distinct type instead of object?

Either way you would need to stop the insane amount of casts and type checks.  Currently for every resolve value there's converting to object and then to type and checking input type is correct format for every resolver ever.

I would suggest merging all the value resolvers into [`ExpressionBasedResolver<TSource, TMember>`](https://github.com/AutoMapper/AutoMapper/blob/65331c16a256882b481b8166f51c3cd36566d2eb/src/AutoMapper/Execution/DelegateBasedResolver.cs#L28) and just use that to resolve the property.  The expression will have to be generated correctly in order to work, so once you make the expression work you shouldn't be worrying about type checks.  If you get a null exception error then you would of gotten that error just like if you had gotten if you mapped the property by hand, or used MapFrom function.  Also it will already have the lambda generated for Projection, since the function is compiled from the expression.

**Comment by jbogard** [comment] 2016-03-02 21:44
One step further. We have that one class, PropertyMapMapper something. Most
of that is pointless in most cases, so I'm looking at looping over each of
the property maps and just doing assignment functions for each one.
Collapse resolvers, yeah those right now are too abstract. I think we can
build expressions to do this:

`dto.Bar = src.Baz;`

And build out whole plans for each property map. No more casts or
boxing/unboxing.

**Comment by TylerCarlson1** [comment] 2016-03-02 22:51
I see the problem is at that point if the type maps don't match you have to new Maps. which means you need to do `dto.Bar = Mapper.Map(src.Baz);`

Looking at it more I think the first, and possibly biggest performance gaining step is to destroy all existing value resolvers and move towards expressions.  In the benchmark it's using PropertyMember resolver most predominantly, and probably is for 99%.  If you move from using property info.GetValue to Expresion there's a big performance gain just in doing that. [Example](http://www.palmmedia.de/Blog/2012/2/4/reflection-vs-compiled-expressions-vs-delegates-performance-comparision) Executes 9 times faster than reflection on the property info.

So I would say start with `src => src.Baz;` expression and compile it into a func, instead of calling `src => propertyInfo.GetValue(src, null);` and get the boost there.  Also you still have src => src.Baz allready as a lamdba expression, so no need to translate it for projeciton, so slight performance increase there as well

**Comment by TylerCarlson1** [comment] 2016-03-02 23:13
I'm going to try to see if I can internal refactor this so that it uses expressions and try to submit a PR for this.

**Comment by jbogard** [comment] 2016-03-03 00:24
I don't think you can kill resolvers completely. People use the type based
versions with DI to instantiate resolvers.

That can still be built to an expression too. It's just a scenario I'd
still want to support.

**Comment by TylerCarlson1** [comment] 2016-03-03 01:02
I did some playing with purely with casting back and forth through the object.

Changing the manual mapper in the benchmark to
```
object source = _source;
		    object baseDate = ((ModelObject) source).BaseDate;
		    object sub2 = ((ModelObject) source).Sub2;
		    object sub2PropertyName = ((ModelSubObject) sub2).ProperName;
            object sub = ((ModelObject)source).Sub;
            object subPropertyName = ((ModelSubObject)sub).ProperName;
            object subA = ((ModelObject)source).Sub;
		    object subSubSub = ((ModelSubObject) subA).SubSub;
            object subSubSubIAmACoolProperty = ((ModelSubSubObject)subSubSub).IAmACoolProperty;
            object subWithExtraName = ((ModelObject)source).SubWithExtraName;
		    object subWithExtraNamePropertyName = ((ModelSubObject) subWithExtraName).ProperName;

            var destination = new ModelDto
				{
					BaseDate = (DateTime)baseDate,
					Sub2ProperName = (string)sub2PropertyName,
					SubProperName = (string)subPropertyName,
					SubSubSubIAmACoolProperty = (string)subSubSubIAmACoolProperty,
					SubWithExtraNameProperName = (string)subWithExtraNamePropertyName
            };
```

Made the execution take 1.64 times longer than the original code.
This is as close as I can get to simulating Automapper's constant boxing and unboxing from object, so the performance might not look like this in automapper but it highlights a point about how bad it is.

Also I recend my statements about PropertyInfo using GetValue.  It's using expressions, but it's still converting the object to and from type, so the performance hit is there.

So first thing is make IValueResolver generic and stop these casting, and try to combine into a single expression.  Still going to look at doing a PR.

**Comment by jbogard** [comment] 2016-03-03 01:20
Maybe the Value resolver one first? I think it'll look just like the type
converter signature.

**Comment by jbogard** [comment] 2016-03-03 04:07
Ha, nevermind. The IValueResolver piece is actually pretty hard to make generic. You can redirect the input of the value resolver from the parent object to a different property.

Perhaps the better solution is to have the property map just receive all the metadata information about an actual property chain, and skip it going through value resolvers.

I'm thinking the property map decision tree looks something like:

- PropertyChain/MapFrom? Create expression to resolve AND set, and compile it
- Else create an action that does basically what the existing stuff does

This might be a preeeeetty big refactoring. But, I think the TypeMapObjectMapperRegistry class and all the things inside it can be just pre-figured out and plugged into the PropertyMap directly.

**Comment by TylerCarlson1** [comment] 2016-03-03 05:31
I'm working on making IValueResolver generic, but I'm using non generic calls atm.  What I'm trying to do now is make it so IValueResolver has an Expression that can be accessed, so from that point I can aggregate the expressions together to get a super expression and compile that.

Also for setting value not casting it to object and back would be beneficial as well as not casting the value resolvers.

**Comment by lbargaoanu** [comment] 2016-03-03 09:20
Expressions are nice for simple things, but when they get complicated I think no extra performance is worth the complexity. Pareto rules :)

**Comment by TylerCarlson1** [comment] 2016-03-03 15:49
@lbargaoanu ProjectTo would disagree with that statement.

I got a some simple examples working with compiled expression, but I need to go further to get the better overall performance gain.  PropertyMaps must be generic so I'm not casting results to object.  Also TypeMaps and possibly ResolutionContexts must be generic so not to cast source or resolutioncontext.source from object to source type, as well as setting the property not casting as well.  It will become more and more like ProjectTo, but with ResolutionContext thrown into the mix and compiling the expressions and calling them passing in resolution context.

**Comment by lbargaoanu** [comment] 2016-03-03 15:52
ProjectTo _has to_ work with expressions.

**Comment by jbogard** [comment] 2016-03-03 16:27
So we can't make PropertyMap etc generic. The delegate generated needs to
be:

Action<object, object, ResolutionContext>

because we're building:

(src, dest, ctxt) => ((Source)src).FooBar = ((Dest) dest).Foo.Bar;

There's no boxing/unboxing in the assignments here, the casts aren't really
expensive. It's the levels of indirection and a Context.Mapper.Map mapping
call that's expensive.

**Comment by jbogard** [comment] 2016-03-03 17:19
The expression part though could be the generic version:

(Source src, Dest dest) => dest.FooBar = src.Foo.Bar;

Then I can wrap the resulting delegate with more complex stuff, but using
the Funcs instead of Expressions:

(src, dest, ctxt, propertyMap) => dest.FooBar = propertyMap.Condition(src,
dest, ctxt) ? dest.FooBar : src.Foo.Bar

So for simple cases we can build an expression for the whole assignment,
for more complex versions we can build a func. This is kinda what I did
here:

https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/PropertyMap.cs#L113

**Comment by TylerCarlson1** [comment] 2016-03-03 17:52
Yea I'm trying to build an expression and compile it to set _valueResolverFunc.

I got that to work with non-resolvers, haven't tried resolvers yet, but to get it to work I had to convert the result back to object.

Going to be a really BIG refactoring to get this all working.

Right now I'm thinking if resolutionContext is more or less to keep position of what's being mapped and what the parent map is, then shouldn't it not be used in resolve using and just kept tracked of independently.  Or generated only on exception for debugging purposes.

**Comment by TylerCarlson1** [comment] 2016-03-03 17:58
@jbogard I see what you are trying to accomplish.  I'm looking at generalizing it for everything, instead of having YET ANOTHER if statement and special case for Mapping.  I think if you are going to try to build and cache a complete property map, you should cache the entire map.  The way you would do this is put TryCatches into the Cahced code, so that you preserve the same error debugging functionality.

**Comment by jbogard** [comment] 2016-03-03 18:20
I don't know if you're going to get there with expressions though, with all
that conditional mapping. I spiked out collapsing the TypeMapRegistry thing
to one class, that made it a lot easier to understand what was going on
first.

So it might be easier to combine Funcs than build one whole expression. At
least at the beginning, otherwise it'd be a huuuuge effort.

**Comment by TylerCarlson1** [comment] 2016-03-03 19:09
I'll see how far down the rabbit hole I can get.
The end all best scenario I think would be a fully realized expression that would handle all the conditions and expand the sub mappings into expressions, while making sure exception handling didn't change.  Buuuuuut I don't think I'll get there anytime soon.  I might get things working in a partially expression based state, but then I don't know if there can be any significant performance gain.

We'll see.  Most likely I'll throw my hands up in the air and surrender to the complexity of the problem, but I'll enjoy the challenge till then. :D

**Comment by jbogard** [comment] 2016-03-03 20:02
The idea for me behind the perf increase is that today we evaluate all the
conditions for a property map, every single time. Instead, we'd build up
the plan based on how they've configured. Like today we evaluate the
condition every single time, regardless if they've actually supplied a
condition or not.

**Comment by TylerCarlson1** [comment] 2016-03-04 05:02
Looks like there's quite a few things that can be done to improve performance in many different areas.
I'm finding easy optimizations while trying to make a complete overhaul.

I don't know how I would make everything expressions, IValueResolvers looks like a good first step though.  At least you are guaranteed 1 or 2 constant casting, and possibly none.

**Comment by TylerCarlson1** [comment] 2016-03-22 03:54
Ok I learned how to do multi-lined expression generation.  Don't try to generate a foreach loop dynamically.

I was able to do recursive calls through expressions and mappings and Keeping the function calls Generic and generating the generic method call for the expression.  Got 300% performance increase from compiling expressions and skipping converting types.  Maybe more with sub objects that needed to get recursively called.  (Didn't have to bother with GetType to get the cached expression info.)

BTW how goes it with Roslyn?  Expressions always a pain when you get back in.

**Comment by jbogard** [comment] 2016-03-22 04:13
Roslyn isn't supported in many platforms so meh.

Shouldn't need a for each loop dynamically, should be able to precalculate
a list of statements from each PropertyMap.

Throw up a PR?

**Comment by TylerCarlson1** [comment] 2016-03-22 04:27
I'll look at it more and see.  Still can probably optimize my code some more, so I can figure out performance benefits, like lumping all functions into a single compiled expression block call.

The dyanamic for each loop is more for if you want the object to return as it's list item type, vs object and casting back.  For AutoMapper I think it's more just you don't really care about the type since it's going to go through those steps to make a type map for each object.

**Comment by jbogard** [comment] 2016-03-22 20:51
I should also mention I'm in the process of refactoring PropertyMap and its
configuration to get rid of all of the pre-configuration of runtime
behavior, and deferring it all until Seal. Having the configuration purely
record configuration, then Seal figure out how to put things together into
an execution plan.

**Comment by TylerCarlson1** [comment] 2016-03-22 22:45
ok that sounds good.  Haven't started yet.  Just curious, will you be getting rid of lazy in IMemberResolvers then?

**Comment by TylerCarlson1** [comment] 2016-03-23 05:08
Found something else to work on that's untouched. `IRuntimeMapper.CreateObject`

I'll generate an `Expression<Func<ResolutionContext,object>>` for TypeMap and compile it and use it for CreateObject.

And probaly cache functions for creating types like `ObjectCreator.CreateNonNullValue`and save time having to figure out the default constructor used every time based on type.

**Closed** 2016-05-18 21:24 UTC
