### ISSUE TITLE
Collection property on destination object is overwritten despite Condition() returning false

### ISSUE THREAD

**Issue by ggirard07** [AutoMapper/AutoMapper#2111] opened 2017-05-16 23:34 UTC
### Source/destination types

```csharp
public class Entity
{
    public int Id { get; set; }
    public ICollection<int> List { get; set; }
}
```

### Mapping configuration

```csharp
AutoMapper.Mapper.Initialize(cfg =>
{
    cfg.AllowNullCollections = true;
    cfg.CreateMap<Entity, Entity>().ForMember(o => o.List, opts => opts.Condition((source, destination, sValue) => sValue != null));
});
```
### Expected behavior

When mapping source instance `partial` to destination instance `full`, I expect member `full.List` to not be updated.

Am I misunderstanding something? I thought it would work as
- Condition is defined on the member to prevent update if source member is null.
- Configuration is set to allow null collection in order to prevent `sValue` to be overwritten by en empty collection prior to evaluate Condition.

### Actual behavior

Currently destination instance `full.List` is updated by an empty collection.

### Steps to reproduce

```csharp
static void Main(string[] args)
{
    AutoMapper.Mapper.Initialize(cfg =>
    {
        cfg.AllowNullCollections = true;
        cfg.CreateMap<Entity, Entity>().ForMember(o => o.Lines, opts => opts.Condition((source, destination, sValue) =>
        {
            if (sValue  == null)
                System.Diagnostics.Debug.WriteLine($"During Update - IsNull");
            else
                System.Diagnostics.Debug.WriteLine($"During Update - NotNull!!! {sValue.Count}");

            return sValue != null;
        }));
    });

    var partial = new Entity
    {
        OrderId = 1,
        Lines = null
    };

    var full = new Entity
    {
        OrderId = 10,
        Lines = new List<int>() { 1, 2, 3 }
    };

    System.Diagnostics.Debug.WriteLine($"Prior Update {full.Lines.Count}");

    AutoMapper.Mapper.Map(partial, full);

    System.Diagnostics.Debug.WriteLine($"After Update {full.Lines.Count}");
}
```

**Comment by lbargaoanu** [comment] 2017-05-17 05:06
Duplicate of  #1918.

**Closed by lbargaoanu** 2017-05-17 05:06 UTC
