### ISSUE TITLE
AutoMapper will not install in a Visual Studio Xamarin Project.

### ISSUE THREAD

**Issue by maxmin88** [AutoMapper/AutoMapper#2150] opened 2017-06-18 19:12 UTC
When using NuGet to install AutoMapper get this error.

Could not install package 'AutoMapper 6.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any way to fix this?

**Comment by lbargaoanu** [comment] 2017-06-18 19:25
Duplicate of #1531.

**Closed by lbargaoanu** 2017-06-18 19:25 UTC
