### ISSUE TITLE
nest collection is clear when using Condition but not Ignore

### ISSUE THREAD

**Issue by hitlcy** [AutoMapper/AutoMapper#1940] opened 2017-02-03 01:21 UTC
I'm expecting the same behavior 
.ForMember(m => m.Items, opt => opt.Condition(src =>false )
and
.ForMember(m => m.Items, opt => opt.Ignore()
but they are not the same. 
When using the first one. the array Items will always be cleared. 
By the way, the code works fine on 5.0.2 but broken on 5.1.1 and 5.2.0.

see my code below
class class1
		{
			public string Name { get; set; }
			public string[] Items { get; set; }
		}

		class class2
		{
			public string Name { get; set; }
			public string[] Items { get; set; }
		}

		static void Main(string[] args)
		{

			var config = new MapperConfiguration(cfg =>
			{
				cfg.CreateMap<class1, class2>()
					.ForMember(m => m.Items, opt => opt.Condition(src =>false )
					//.ForMember(m => m.Items, opt => opt.Ignore()
			);

			});
			var mapper = config.CreateMapper();

			var obj1 = new class1 {Name="name"};
			var obj2 = new class2 {Items = new []{"item1", "item2"}};
		

			mapper.Map(obj1, obj2);

			Console.WriteLine(obj2.Items.Length);//expected to see 2 here

		}

**Comment by TylerCarlson1** [comment] 2017-02-03 02:31
Check PreCondition it happens before resolving and should work like Ignore

**Comment by lbargaoanu** [comment] 2017-02-03 07:02
Duplicate of #1918.

**Closed by lbargaoanu** 2017-02-03 07:02 UTC
