### ISSUE TITLE
IValueResolver with parameterized constructor

### ISSUE THREAD

**Issue by lisamariet** [AutoMapper/AutoMapper#2028] opened 2017-03-27 10:39 UTC
I have written my own IValueResolver but I want it to have an interface injected at runtime from Ninject. How can I archive this?

Configure:
```
CreateMap<SourceEntity, DestModel>()
               .ForMember(dest => dest.IsOk, opt => opt.ResolveUsing<MyResolver>());
```

Resolver:
```
public class MyResolver : IValueResolver<SourceEntity, DestModel, bool>
        {
            private readonly IMyFacadeService _myFacadeService;

            public MyResolver (IMyFacadeService myFacadeService)
            {
                _myFacadeService= myFacadeService;
            }

            public bool Resolve(SourceEntity source, DestModel destination, bool destMember, ResolutionContext context)
            {
                var returnedBoolValue = Task.Run(async () => await _myFacadeService.CallSomeMethod(source)).Result;

                return returnedBoolValue;
            }
        }
```

I had a look at the documentation where it says "ConstructBy" should be possible, but I cannot get that to work. It says return of opt.ResolveUsing<CustomResolver>() is void so I cannot add .ConstructedBy

```
Mapper.Initialize(cfg => cfg.CreateMap<Source, Destination>()
        .ForMember(dest => dest.Total, 
            opt => opt.ResolveUsing<CustomResolver>().ConstructedBy(() => new CustomResolver())
        );
```

But even if this was possible. How to actually add the Ninject Kernal binding for IMyFacadeService ?

Regards,

**Comment by lbargaoanu** [comment] 2017-03-27 11:46
Duplicate of #2021. Read that and the older issue. Get back to us if things are still not clear.

**Closed by lbargaoanu** 2017-03-27 11:46 UTC

**Comment by lisamariet** [comment] 2017-03-27 12:52
Okay, but it is still not answering my question on how to do this with dependency injection, which is my question?

This only answers the error in documentation about .ConstructedBy

**Comment by lbargaoanu** [comment] 2017-03-27 13:08
Yes, it does :), at least about the AM part. But if you mean how to do it with NInject, that's a question for another forum. In a nutshell the answer is also in the [docs](https://github.com/AutoMapper/AutoMapper/wiki/Dependency-injection).

**Comment by lisamariet** [comment] 2017-03-28 06:33
I finally got it... here is the answer for anyone else looking:

```
// Add value resolver to Ninject Kernel
Kernel.Bind<IValueResolver<SourceEntity, DestModel, bool>>().To<MyResolver>(); 

var mapperConfig = MappingConfigFactory.CreateConfiguration();  //Adds all profiles

// Send in instances for the Resolvers in use
var mapper = mapperConfig.CreateMapper(type => Kernel.Get<IValueResolver<SourceEntity, DestModel, bool>>());
```
