### ISSUE TITLE
Automapper Update entity field if not null fails if entity field is not nullable

### ISSUE THREAD

**Issue by MattHartz** [AutoMapper/AutoMapper#1869] opened 2016-12-27 19:27 UTC
Hi,

Sorry for the probably confusing title.  Basically, I am trying to update an entity with an object, and only update the fields from that object where those fields are not null.  For instance, say i have an object with two date fields and in our API they are both nullable.  But, when i send an object with both of them set to null, the one that is nullable keeps the same date, while the one that isn't nullable gets set to the default date.  Any ideas on what might be causing this?  Here is my map

```javascript 
CreateMap<RequirementUpdateIn, Requirement>()
     //.ForMember(s => s.RequirementType, o => o.MapFrom(d => (int)d.Type))
     .ForAllMembers(m => m.Condition((source, target, sourceValue, targetValue) => sourceValue != null));
```

From my understanding, the forallmembers should skip the null dates and leave the dates pulled back from the entity model the same.

Let me know if you have any questions!

Thanks

**Comment by lbargaoanu** [comment] 2016-12-27 21:29
There are workarounds. See https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-265670132 and the discussion there.

**Comment by MattHartz** [comment] 2016-12-27 21:34
Hi @lbargaoanu , is there a preferred way to do what you say in that comment using the Profile class?

**Comment by lbargaoanu** [comment] 2016-12-27 21:55
ForAllPropertyMaps should be in Profile if that's what you mean.

**Comment by MattHartz** [comment] 2016-12-27 22:01
Okay, yeah I see it in the Profile definition.  Is there any documentation on using ForAllPropertyMaps? 

Here is a sample of my profile:
```

**Comment by lbargaoanu** [comment] 2016-12-27 22:10
You don't need to override it, just call it as in that example. You can filter the maps you want to change.

**Comment by MattHartz** [comment] 2016-12-27 22:15
Oh I see. Okay, i'll let you know if I have negative results :)

**Comment by MattHartz** [comment] 2016-12-27 22:58
Does it make sense for that to now error on every field that i don't explicitly map? I use an extension method of "IgnoreAllUnmapped" which does

**Comment by jbogard** [comment] 2016-12-28 04:29
Ohhhhh don't do that IgnoreAllUnmapped. Check the upgrade guide in the wiki, there's a much better way to do what you're doing now.

**Comment by MattHartz** [comment] 2016-12-28 04:35
Hi @jbogard ,
Okay, i switched to using MemberList.None.  I assume that is what you are talking about.  I'm still having issues with pm.sourceType being null.  Do i have to supplement everything that isn't mapped with ignore/usedestinationvalue? If so, I tried that and some values are still complaining.

**Comment by jbogard** [comment] 2016-12-28 04:54
Is SourceType always null? Are you seeing an exception?

**Comment by MattHartz** [comment] 2016-12-28 04:59
Yeah, here is my map.
```C#
CreateMap<RequirementUpdateIn, Requirement>(MemberList.None)
                .ForMember(d => d.IsActive, o => o.Ignore())
                .ForMember(d => d.CorporateOffice, o => o.Ignore())
                .ForMember(d => d.CorporateOfficeId, o => o.Ignore())
                .ForMember(d => d.CreatedBy, o => o.Ignore())
                .ForMember(d => d.CreatedOn, o => o.UseDestinationValue())
                .ForMember(d => d.ModifiedBy, o => o.Ignore())
                .ForMember(d => d.ModifiedOn, o => o.Ignore())
                .ForMember(d => d.ProgramRequirements, o => o.Ignore())
                .ForMember(d => d.RequirementType, o => o.Ignore())
                .ForMember(d => d.Type, o => o.Ignore());
```
And here is the exception:
Additional information: Value cannot be null. (for pm.SourceType).  pm is for RequirementType in this situation.  RequirementType is a virtual object from entity.
I realize this is a terrible map, it's just for debugging purposes.

**Comment by lbargaoanu** [comment] 2016-12-28 07:10
Try excluding ignored members.

**Comment by MattHartz** [comment] 2016-12-28 07:50
@lbargaoanu I added those Ignore lines as an attempt to remedy the error.
```
CreateMap<RequirementUpdateIn, Requirement>(MemberList.None)

**Comment by lbargaoanu** [comment] 2016-12-28 10:55
If there is no corresponding source member, of course SourceType is null :) Just skip them.

**Comment by jbogard** [comment] 2016-12-28 16:10
What @lbargaoanu said - the MemberList enum is only for configuration validation. Ignore does two things - skips mapping if the members match, and skip the member for configuration validation. If you need to skip members in the ForAllMembers, check types inside there.

**Comment by MattHartz** [comment] 2016-12-28 18:08
Okay, so i think i may understand why the sourcetype is null.  This doesn't appear to work with enums, or in my case nullable enum...

**Comment by lbargaoanu** [comment] 2016-12-28 19:00
A repro would help. Make a gist that we can execute and see fail.

**Comment by MattHartz** [comment] 2016-12-28 19:15
Well. I got everything to work this this hokey solution.

Here is my finished solution:
```
CreateMap<RequirementUpdateIn, Requirement>(MemberList.None)
                .ForMember(d => d.IsActive, o => o.Ignore())
                .ForMember(d => d.Type, o => o.ResolveUsing<TypeResolver, RequirementType>(s => s.Type))
                .ForAllMembers(m => m.Condition((source, target, sourceValue, targetValue) => sourceValue != null));

ForAllPropertyMaps(
                pm => Nullable.GetUnderlyingType(pm.SourceType) == pm.DestinationPropertyType,
                (pm, c) => c.ResolveUsing<object, object, object, object>(new NullUpdateResolver(), pm.SourceMember.Name));

class NullUpdateResolver : IMemberValueResolver<object, object, object, object>
        {
            public object Resolve(object source, object destination, object sourceMember, object destinationMember, ResolutionContext context)
            {
                return sourceMember ?? destinationMember;
            }
        }

    class TypeResolver : IMemberValueResolver<RequirementUpdateIn, Requirement, RequirementType, int>
    {
        public int Resolve(RequirementUpdateIn source, Requirement destination, RequirementType sourceMember, int destinationMember, ResolutionContext context)
        {
            return sourceMember == QMerit.ADP.Models.RequirementType.Unknown ? destinationMember : (int)sourceMember;
        }
    }
```

**Comment by jbogard** [comment] 2016-12-28 19:29
For the record I'm not sure that's hokey. This looks like a good use of ForAllMembers and ForAllPropertyMaps.

**Comment by lbargaoanu** [comment] 2016-12-28 20:45
It would be cleaner with a PreCondition, provided someone will add the missing overload.

**Comment by MattHartz** [comment] 2016-12-28 22:30
@jbogard Sorry, it seemed hokey because this seemed to be a weird situation that I haven't had in any of my other maps.  For some reason our other maps didn't need this. ><. But yeah, I'm hoping this should resolve any future issues we have with updating enums and other data types.

@lbargaoanu Precondition for which aspect? Replace the forallmembers condition?

**Comment by lbargaoanu** [comment] 2016-12-29 07:14
For both.

**Comment by lbargaoanu** [comment] 2017-01-23 10:42
Duplicate of #1723.

**Closed by lbargaoanu** 2017-01-23 10:42 UTC
