### ISSUE TITLE
Android & Portable Class library issue

### ISSUE THREAD

**Issue by jcmm33** [AutoMapper/AutoMapper#1014] opened 2016-01-06 15:23 UTC
We have a simple Xamarin Android solution which has a Portable Class Library in the solution.

Both the main application and the PCL have AutoMapper 4.1.1 installed.

We however see an issue when we try to create a map in the main application when it references a class in the PCL which is a custom type converter. Specifically we are shown the error 

The type 'TypeConverter<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'AutoMapper, Version=4.1.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'.

Now, if we move the class which uses this Type from the PCL into the main application it then compiles file, implying that in fact the main application does have references to the assembly referenced above.

Source in PCL:

```
    public class Source
    {
        public int Name { get; set; }
    }

    public class Destination
    {
        public int FinalName { get; set; }
    }

    public class Converter:TypeConverter<Source,Destination>
    {
        protected override Destination ConvertCore(Source source)
        {
            return new Destination() {FinalName = source.Name};
        }
    }
```

Source in main Application:

```
  public class MainActivity : Activity
    {
        int count = 1;

        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            Mapper.CreateMap<Source, Destination>().ConvertUsing<Converter>();

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);

            // Get our button from the layout resource,
            // and attach an event to it
            Button button = FindViewById<Button>(Resource.Id.MyButton);

            button.Click += delegate { button.Text = string.Format("{0} clicks!", count++); };
        }
    }
```

The Mapper.CreateMap line is the one with the error when Converter is in the PCL instead of the main application.

I've placed a VS.NET 2015 solution for the above classes here to highlight the issue we are seeing. http://1drv.ms/1PNf4Ms

**Comment by lbargaoanu** [comment] 2016-01-07 09:49
I don't know much about PCL-s. But what I can see is that your projects reference different versions of AutoMapper. The library references 

    <Reference Include="AutoMapper, Version=4.1.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoMapper.4.1.1\lib\portable-net45+win+wpa81+wp80+MonoAndroid10+Xamarin.iOS10+MonoTouch10\AutoMapper.dll</HintPath>

and the app

    <Reference Include="AutoMapper, Version=4.1.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\AutoMapper.4.1.1\lib\MonoAndroid\AutoMapper.dll</HintPath>

I would guess they should both reference the PCL :)

**Comment by jcmm33** [comment] 2016-01-07 09:54
The references weren't hand crafted by me, but are as a result of using Nuget within the solution, so if they should be the same assembly then perhaps the packages need to be updated to reflect this.

**Comment by lbargaoanu** [comment] 2016-01-07 10:32
The latest version from MyGet only supports .NET Core and .NET 4.5, no more PCL-s.

**Comment by jbogard** [comment] 2016-01-07 14:00
Are both those assemblies signed? The MonoAndroid and the PCL one?

**Comment by jcmm33** [comment] 2016-01-07 14:51
Strong Name Utility reports : 

```
E:\Temp\AutomapperPCLBehavior\packages\AutoMapper.4.1.1\lib>sn -v MonoAndroid\Automapper.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

MonoAndroid\Automapper.dll does not represent a strongly named assembly


E:\Temp\AutomapperPCLBehavior\packages\AutoMapper.4.1.1\lib>sn -v portable-net45+win+wpa81+wp80+MonoAndroid10+Xamarin.iOS10+MonoTouch10\AutoMapper.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'portable-net45+win+wpa81+wp80+MonoAndroid10+Xamarin.iOS10+MonoTouch10\AutoMapper.dll' is valid
```

**Comment by jbogard** [comment] 2016-01-07 15:22
Well that would be why, the MonoAndroid compiler doesn't let me strong-name anything. Bummer.

As a workaround, you can manually add a reference from your MonoAndroid project to the PCL library. It's hokey, but this is something that will be fixed in the future by NuGet directly through the .NET standard platform. https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by onovotny** [comment] 2016-01-07 15:32
AFAIK, you can sign Xamarin projects but the UI isn't exposed. You have to manually edit the csproj:

https://github.com/onovotny/ninject/blob/master/src/Ninject/Ninject.Android.csproj#L47-L57

**Comment by jbogard** [comment] 2016-01-18 13:38
@jcmm33 can you try the latest MyGet? I've re-enabled a PCL version of AutoMapper that would be referenced from both projects (and is signed).

**Comment by jcmm33** [comment] 2016-01-18 14:59
@jbogard will do, but it will be a couple of days since I've not been out of hospital long.

**Comment by vinguan** [comment] 2016-03-14 02:22
We gonna have support for PCL and Xamarin.iOS and Xamarin.Android on 4.2 and later?

**Comment by jbogard** [comment] 2016-03-14 15:53
@vinguan I don't know what's not working with the current version, and I'm not a big Xamarin user. Perhaps you can take a crack at seeing what it would take to fix it? I'm more than happy to put out a patch version for this if someone figures out what is wrong.

**Comment by vinguan** [comment] 2016-03-14 22:50
@jbogard The dlls are fine. The problem is in the latest nuget package. It does not target Xamarin.iOS and Xamarin.Android. It is only targeting WindowsPhone8 and Windows8. I think if you change the build to profile 259, everything it's gonna be okay.

**Comment by jbogard** [comment] 2016-05-18 21:13
Confirmed this is working on alpha channel of Xamarin.

**Closed by jbogard** 2016-05-18 21:13 UTC
