### ISSUE TITLE
Map a domain entity to a custom view model

### ISSUE THREAD

**Issue by TDK1964** [AutoMapper/AutoMapper#984] opened 2015-11-12 11:14 UTC
What is the best way to map a domain entity to a custom view model given the following scenario?

These are the domain objects

    public class PurchaseOrderHeader
    {
        public int Id { get; set; }
        public byte Status { get; set; }
        public DateTime OrderDate { get; set; }
    }
    public class PurchaseOrderDetail
    {
        public int Id { get; set; }
        public int PurchaseOrderId { get; set; }
        public int ProductId { get; set; }
    }

View Models
In PurchaseOrderDetailVM there's an additional property not in the PurchaseOrderDetail model/table e.g. joining the PurchaseOrderDetail and Product tables in a SQL query.

    public class PurchaseOrderHeaderVM
    {
        public int Id { get; set; }
        public byte Status { get; set; }
        public DateTime OrderDate { get; set; }
    }
    public class PurchaseOrderDetailVM
    {
        public int Id { get; set; }
        public int PurchaseOrderId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; } 
    }

Repository Interface

    public interface IPurchaseOrderRepository
    {
        PurchaseOrderHeader GetById(int id);
        IEnumerable<PurchaseOrderDetail> GetByHeaderId(int headerId);
    }

If I just do a straight forward mapping like this in the controller everything works great but obviously ProductName is not available because it's not part of the domain entity PurchaseOrderDetail

    public ActionResult Details(int id)
    {
        var header = _purchaseOrderRepository.GetById(4);
        var detail = _orderDetailRepository.GetByHeaderId(4);

        var headerModel = Mapper.Map<PurchaseOrderHeader, PurchaseOrderHeaderVM>(header);
        var detailModel = Mapper.Map<List<PurchaseOrderDetailVM>>(detail);

        var model = new EditPageViewModel(headerModel, detailModel);
        return View(model);
    }

My Visual Studio projects are separated like this 
Demo.Model - domain objects etc
Demo.Repository - data access etc
Demo.Web - UI

I thought about creating a ReadOnly ViewModel in the Demo.Model project but this feels wrong as the models only concern is to contain the clean POCOs

**Comment by lbargaoanu** [comment] 2015-11-12 12:04
You can use ProjectTo, so you return ViewModels directly from the database. [Example](https://lostechies.com/jimmybogard/2014/03/11/efficient-querying-with-linq-automapper-and-future-queries/).

**Comment by TDK1964** [comment] 2015-11-12 12:36
I don't use entity framework, will this scenario still work?

**Comment by lbargaoanu** [comment] 2015-11-12 12:38
Yes, if LINQ provider supports it.

**Comment by TDK1964** [comment] 2015-11-12 13:10
I'm using the Dapper (ORM) and would prefer not to use LINQ, is there another way this can be achieved?

**Comment by lbargaoanu** [comment] 2015-11-12 13:16
[ResolveUsing](https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers) for the missing properties might help.

**Comment by TDK1964** [comment] 2015-11-12 13:56
I don't think ResolveUsing is the solution. My particular problem must be a common one, I can't believe this hasn't come up before. The only way I can see to resolve is add the view models into the Demo.Model project as both Repository and Web projects reference the Model project?
Seems wrong though.

**Comment by lbargaoanu** [comment] 2015-11-12 13:58
It is common and the solution is ProjectTo,

**Comment by TDK1964** [comment] 2015-11-12 14:12
To be honest I'm struggling a bit. Any chance you could give me a starter example using my code above?

**Comment by lbargaoanu** [comment] 2015-11-12 14:20
If I understand you correctly the problem is how to fill the missing data, ProductName for example. Without ProjectTo you have to fetch the data you need and then Map it to your view models. But the source of the data, your entities I imagine, must have everything you need. In EF you would have a PurchaseOrderDetail.Product object property with the name, I don't know about Dapper.

**Comment by TDK1964** [comment] 2015-11-12 15:14
Actually the Northwind database has a very similar schema to my own, could you possibly create an example based on that. I'm sure others would benefit from a working example?

**Comment by lbargaoanu** [comment] 2015-11-12 15:16
If you have a concrete issue with AutoMapper I can help. More general questions are better asked on StackOverflow.

**Comment by jbogard** [comment] 2015-11-12 15:20
So, I would say your repositories are wrong. Instead of partitioning access around entities, partition around use cases. You've made an assumption around how users would access data (one entity isolated at a time) versus how they actually access data (using joins and such).

This is why folks gravitate towards CQRS and separate read/write models. Having reads not go through your entities, and go straight from Dapper to ViewModel. I do this *all the time* and it allows your read models to not be compromised based on what the write models need.

For a concrete example using AutoMapper, check out my ContosoUniversity project:

https://github.com/jbogard/ContosoUniversity/blob/master/src/ContosoUniversity/Features/Course/Index.cs

I separate the read and write models out explicitly, AutoMapper being simply a means to create the Select projection.

**Comment by lbargaoanu** [comment] 2015-11-26 15:07
@TDK1964 Can you please close your issue?

**Comment by jbogard** [comment] 2016-01-18 16:07
Closing.

**Closed by jbogard** 2016-01-18 16:07 UTC
