### ISSUE TITLE
EF Core 2.0: ProjectTo<T>().ToListAsync() hangs forever

### ISSUE THREAD

**Issue by geirsagberg** [AutoMapper/AutoMapper#2257] opened 2017-08-07 15:37 UTC
### Expected behavior

`await ...ProjectTo<T>.ToListAsync()` should return a result

### Actual behavior

Program hangs forever on `await ProjectTo<T>.ToListAsync()`

### Steps to reproduce

```csharp
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.EntityFrameworkCore;

namespace ToListAsyncBugConsole
{
    public class MyContext : DbContext
    {
        public DbSet<Company> Companies { get; set; }
        public DbSet<Employee> Employees { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Database=ToListAsyncBug;Trusted_Connection=true;");
        }
    }

    public class Company
    {
        public int Id { get; set; }
        public ISet<Employee> Employees { get; set; } = new HashSet<Employee>();
    }

    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Required]
        public int CompanyId { get; set; }

        public Company Company { get; set; }
    }

    public class CompanyDto
    {
        public int Id { get; set; }
        public IList<EmployeeDto> Employees { get; set; } = new List<EmployeeDto>();
    }

    public class EmployeeDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class Program
    {
        public static async Task Main(string[] args)
        {
            var config = new MapperConfiguration(c => c.CreateMissingTypeMaps = true);

            using (var context = new MyContext()) {
                context.Database.EnsureCreated();

                if (!context.Companies.Any()) {
                    context.Companies.Add(new Company
                    {
                        Employees = {
                            new Employee {
                                Name = "Fooman"
                            }
                        }
                    });
                    context.SaveChanges();
                }

                var projectTo = context.Companies.AsNoTracking().ProjectTo<CompanyDto>(config);
                var companies1 = projectTo.ToList();
                var companies2 = await projectTo.ToListAsync(); // Hangs forever on this line
            }
        }
    }
}
```

**Comment by geirsagberg** [comment] 2017-08-07 15:38
Not sure if this problem exists in EF Core 1.1

**Comment by lbargaoanu** [comment] 2017-08-07 15:41
Duplicate of #2184.

**Closed by lbargaoanu** 2017-08-07 15:41 UTC
