### ISSUE TITLE
InvalidOperationException : ValueFactory attempted to access the Value property of this instance.

### ISSUE THREAD

**Issue by timmkrause** [AutoMapper/AutoMapper#1847] opened 2016-12-09 15:13 UTC
This issue was introduced to us after updating to version 5.2.0.

We have a test helper which creates our mapper and adds profiles for us via reflection (we also tried to wrap it with a lock).

```
private static IMapper MapAutoMapper()
{
	lock (new object())
	{
		var profiles = from assembly in AppDomain.CurrentDomain.GetAssemblies().Where(x => x.FullName.StartsWith("ProjectName."))
					   from profileType in assembly.GetExportedTypes()
					   where typeof(Profile).IsAssignableFrom(profileType) && !profileType.GetTypeInfo().IsAbstract
					   select (Profile)Activator.CreateInstance(profileType);

		var config = new MapperConfiguration(cfg =>
		{
			foreach (var profile in profiles)
			{
				cfg.AddProfile(profile);
			}
		});

		return config.CreateMapper();
	}
}
```

This often throws the exception down below on our build server (TeamCity). This should be related to a multi-threading issue as Lazy<> is involved which is not thread-safe, right?

```
System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at AutoMapper.Mappers.ConvertMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Shared.TestHelper.WithFakes.MapAutoMapper() in C:\Something\Something\Project\Path\WithFakes.cs:line xx
```

Any ideas?

**Comment by lbargaoanu** [comment] 2016-12-09 15:23
Initialization should happen on a single thread, before any other use of AM. Only after the init phase is done, you're free to share the resulting mapper object. So if you have a repro in these conditions, I want to see it :)

**Comment by lbargaoanu** [comment] 2016-12-09 15:28
It might make sense if you're not on 5.2.0.

**Comment by timmkrause** [comment] 2016-12-09 15:29
Sorry, I forgot to mention that this code ran just fine before version 5.2.0. What has changed since then that it worked perfectly fine before? If this is the only way... then we have to think about how to handle this... Guessing that TeamCity kicks off several threads for running the xUnit tests.

**Comment by lbargaoanu** [comment] 2016-12-09 15:37
The static Mapper seems more appropriate for this case. But you still have to call Initialize only once.

**Comment by lbargaoanu** [comment] 2016-12-09 15:40
And another thing, lock(new object()) doesn't lock anything. Object identity is key here. But this code doesn't look good regardless.

**Comment by timmkrause** [comment] 2016-12-09 15:44
Yeah you're right.

What's wrong with the code? Simple approach. Look for profiles, add them, create an instance.

The question still remains regarding what has changed under the covers that it doesn't work anymore with 5.2.0.

**Comment by lbargaoanu** [comment] 2016-12-09 15:46
Why the init code runs more than once? That's unexpected.

**Comment by jbogard** [comment] 2016-12-09 15:57
We did a lot of config changes underneath the covers.

But I'd suggest you use Lazy<T> and not this locking. It's smarter than you
or I about this sort of thing

**Comment by lbargaoanu** [comment] 2016-12-09 16:14
In all fairness, no locks are needed here, because there is no shared state. The shared state is in AM, see #1848. But when you do smth unexpected, things happen :)

**Comment by TylerCarlson1** [comment] 2016-12-09 16:24
Hmm the exception message says the issue is thrown in ConvertMapper which looks like an AutoMapper bug.  Looks like ConvertMapper isn't thread safe when resolving multiple instances of IMapper at the same time is my guess.

**Comment by lbargaoanu** [comment] 2016-12-09 16:25
No init code in AM should be thread safe. The instances were shared because they were placed in statics.

**Comment by timmkrause** [comment] 2016-12-09 16:39
We have done it in with Lazy<> before version 5.2.0. Since 5.2.0 we have this issue even with Lazy.
Then we tried it without lazy. And THEN we tried it with this ugly lock.

Before 5.2.0:

`private static readonly Lazy<IMapper> AutoMapper = new Lazy<IMapper>(MapAutoMapper);`

**Comment by lbargaoanu** [comment] 2016-12-09 17:38
But this would mean it happens all the time, even when you init once, which is clearly a bug. But it might depend on your particular setup. So a repro would help.

**Comment by lbargaoanu** [comment] 2016-12-09 18:06
I say that because I see the error when calling init more than once on different threads, but I don't see it under a lock, let alone calling once.

**Comment by timmkrause** [comment] 2016-12-12 09:24
Sorry, currently we don't have the time for a repro. We're downgrading to 5.0.2 again.
Others seem to have faced a problem with Lazy<T> as well: https://github.com/elmah/Bootstrapper/issues/5

Maybe this helps?

I will try to build a repro next week if the provided link doesn't help.

**Comment by lbargaoanu** [comment] 2016-12-12 09:41
Hmm, no :) We only fix issues we can see for ourselves. I don't think it's possible for that error to appear unless you call init code concurrently.

**Comment by timmkrause** [comment] 2016-12-12 10:04
And this happens... We have this `WithFakes` class from which test classes inherit, so in case of multiple threads executing unit tests this will happen I would assume.

**Comment by lbargaoanu** [comment] 2016-12-12 10:18
Well, yes, but this should be worked around with a lock, or even better by calling init once. Above you said that it fails also when calling init once with Lazy and that seems impossible.

**Comment by timmkrause** [comment] 2016-12-12 10:35
The docs say that even Lazy is not thread safe and shouldn't be initialized more than once by multiple threads... 

> "The Lazy<T> instance is not thread safe; if the instance is accessed from multiple threads, its behavior is undefined. Use this mode only when high performance is crucial and the Lazy<T> instance is guaranteed never to be initialized from more than one thread. If you use a Lazy<T> constructor that specifies an initialization method (valueFactory parameter), and if that initialization method throws an exception (or fails to handle an exception) the first time you call the Lazy<T>.Value property, then the exception is cached and thrown again on subsequent calls to the Lazy<T>.Value property. If you use a Lazy<T> constructor that does not specify an initialization method, exceptions that are thrown by the default constructor for T are not cached. In that case, a subsequent call to the Lazy<T>.Value property might successfully initialize the Lazy<T> instance. If the initialization method recursively accesses the Value property of the Lazy<T> instance, an InvalidOperationException is thrown."

https://msdn.microsoft.com/de-de/library/system.threading.lazythreadsafetymode(v=vs.110).aspx

Maybe it is as easy as using `LazyThreadSafetyMode.ExecutionAndPublication`?

> "Locks are used to ensure that only a single thread can initialize a Lazy<T> instance in a thread-safe manner."

**Comment by lbargaoanu** [comment] 2016-12-12 10:41
By default it's thread safe.

**Comment by ilmax** [comment] 2016-12-14 14:05
Same error here, and 5.1.1 work fine. Will investigate further

**Comment by desertrambler** [comment] 2016-12-16 03:58
I am having the same error. It only happens when I try to run all our tests at once. I create a new mapper in each test class, but if all of the tests are running at the same time, then we have multiple threads, each creating a mapper in the test class, so we get this collision. This didn't happen before upgrading to 5.2.0 - we were able to run all of them at one time just fine. Each of our test classes has code in the constructor that looks like this:

`                // create the mapping configuration
                var config = new MapperConfiguration
                    (
                    map =>
                    {
                        map.AddProfile<ABCProfile>();
                        map.AddProfile<XYZProfile>();
                    });

                // assert that the configuration is valid
                config.AssertConfigurationIsValid();

                this.mapper = config.CreateMapper();
`

We are quite dependent on AutoMapper in our application, and having it not work in test or on a Build Server when it runs all of the tests for an application at one time, is not really acceptable.

What is the correct way to solve this problem?

**Comment by jbogard** [comment] 2016-12-16 14:38
We've got a pending PR for this one.

**Closed** 2016-12-19 15:25 UTC

**Comment by lbargaoanu** [comment] 2016-12-19 19:50
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by timmkrause** [comment] 2017-01-12 14:55
@lbargaoanu, @jbogard: Successfully tested this on TeamCity with MyGet package version 5.3.0-alpha-01276 today. Ran 3 builds without errors. Thank you so much! Looking forward to the next version! 👍
