### ISSUE TITLE
Can't install Automapper 5.0 into Windows 10 UWP

### ISSUE THREAD

**Issue by SamJSchoenberg** [AutoMapper/AutoMapper#1448] opened 2016-07-05 18:47 UTC
Steps to reproduce:

 - From Visual Studio 2015, Update 2, create a new project.
 - Go to Templates -> Windows -> Universal -> Blank App (Universal Windows)
 - Right-click on the project in the solution explorer and select "Manage NuGet Packages..."
 - Click the Browse tab, and search for "AutoMapper"
 - select AutoMapper, make sure version 5.0.0 is selected, and click install.

After following those steps, The install fails.  
The same steps work successfully for AutoMapper 4.2.1 and 4.1.1

The output window looks like the following:

>Restoring packages for 'App7'.
Restoring packages for c:\users\omitted\documents\visual studio 2015\Projects\App7\App7\project.json...
Version conflict detected for System.Collections. 
 App7 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> System.Net.Sockets (>= 4.0.0) -> runtime.win.System.Net.Sockets (>= 4.1.0) -> System.Collections (>= 4.0.11) 
 App7 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm (>= 1.0.0) -> System.Collections (= 4.0.10).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'App7'.
Package restore failed. Rolling back package changes for 'App7'.
========== Finished ==========

**Comment by lbargaoanu** [comment] 2016-07-05 18:51
Try the MyGet build. If that works, you can close the issue.

**Comment by jbogard** [comment] 2016-07-05 19:05
Duplicate of #1439

**Closed by jbogard** 2016-07-05 19:05 UTC

**Comment by SamJSchoenberg** [comment] 2016-07-05 19:34
@jbogard According to that issue, installing the MyGet version resolved the issue, but I'm still unable to install it.  

I set up a package source pointing to https://www.myget.org/F/automapperdev/api/v2 and attempted to install __Latest prerelease 5.0.1-alpha-01144__, but I got essentially the same error as before

**Comment by jbogard** [comment] 2016-07-05 19:43
What does your project.json look like? Here's mine:

```
{
  "dependencies": {
    "AutoMapper": "5.0.1-alpha-*",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by SamJSchoenberg** [comment] 2016-07-05 19:47
So, I've just changed `"Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"` to  `"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0"`, and it worked.

**Comment by jbogard** [comment] 2016-07-05 19:55
Brilliant! The 5.2 platform targets all the .NET Core RTM stuff, for future folks that see this.
