### ISSUE TITLE
Allow using PreConditions with ProjectTo in specific cases (Localization)

### ISSUE THREAD

**Issue by oleg-varlamov** [AutoMapper/AutoMapper#3489] opened 2020-08-26 05:37 UTC
**Use case**

We have an Entity model with localized properties and use any ORM (NHibernate in this example):

```csharp
public class Product {
  public virtual long Id {get; set;}
  public virtual long NameEn {get; set;}
  public virtual long NameIt {get; set;}
  public virtual long NameRu {get; set;}
}
```

and DTO model:

```csharp
public class ProductDto {
  public virtual long Id {get; set;}
  public virtual long Name {get; set;}
}
```

Also we use ProjectTo to make mapping from Entity to DTO.
So now we need to map localized properties (NameEn, NameIt, NameRu) to single DTO property (Name) according to current UI culture. But here we have a problem because Automapper Queryable extension ignored PreConditions.

**Proposal**

Something like this would be very helpful for us:

```csharp
this.CreateMap<Product, ProductDto>()
  .ForMember(d=>d.Name, m=>{
    m.PreCondition(()=>Thread.CurrentThread.CurrentUICulture.ThreeLetterISOLanguageName == "en");
    m.MapFrom(s=>s.NameEn);
  }
  .ForMember(d=>d.Name, m=>{
    m.PreCondition(()=>Thread.CurrentThread.CurrentUICulture.ThreeLetterISOLanguageName == "it");
    m.MapFrom(s=>s.NameIt);
  }
  .ForMember(d=>d.Name, m=>{
    m.PreCondition(()=>Thread.CurrentThread.CurrentUICulture.ThreeLetterISOLanguageName == "ru");
    m.MapFrom(s=>s.NameRu);
  };
```

In our case conditions are not based on source object and only tell either to map source property to concrette destination property or not to map.

Alternatives

We can use conditions right in the query, but it's not a nice solution which leads to many code duplications.

**Comment by lbargaoanu** [comment] 2020-08-26 05:58
Duplicate of #3360. This was discussed many times before, here and on SO. sometimes specifically about localization. You'll just have to choose one of the solutions people used before.

**Closed by lbargaoanu** 2020-08-26 05:58 UTC
Labels: Question

**Comment by oleg-varlamov** [comment] 2020-08-26 06:20
Yes, I saw thread #3360. But my request is different. That question was need conditional mapping based on source object, which means transform PreCondition expression to LINQ. But in my case LINQ hadn't to contain conditional expression.

Regarding that there are many solutions for Localization, i think neither of these solutions would be as elegant as solution with Automapper.

**Comment by lbargaoanu** [comment] 2020-08-26 06:59
A `PreCondition` is smth that gets executed at map time. Apparently you want smth else altogether. If you cannot find what you want, you should ask a new question on SO.
