### ISSUE TITLE
ArgumentException with .Project().To<VM>()

### ISSUE THREAD

**Issue by LinusF** [AutoMapper/AutoMapper#280] opened 2012-12-21 07:52 UTC
I am using EF 6 and generate POCOs from DB by the "EF 5.xDbContext Generator".
My VM-class has all the properties of the generated POCO class.
I create configs for both directions:
           Mapper.CreateMap<MyGeneratedEfPoco, MyVM>();
           Mapper.CreateMap<MyVM, MyGeneratedEfPoco>();

Normal mapping works fine in both directions:
          var vm = Mapper.Map<MyGeneratedEfPoco, MyVM>(model);
           var model = Mapper.Map<MyVM, MyGeneratedEfPoco>(vm);

But 
      var result = dbContext.myGeneratedEfPocos.Project().To<MyVM>(); 
       causes an ArgumentException: Argument types do not match

**Comment by lcalabrese** [comment] 2015-12-08 09:18
+1 on properties mentioned in projection exceptions. I'm trying to track one down right now on a large model.

**Comment by michaelmsm89** [comment] 2016-06-02 21:44
+1 on properties mentioned in projection exceptions

**Comment by jbogard** [comment] 2016-06-03 01:59
Ok I'm all for it. How? What exception do you see today?

**Comment by michaelmsm89** [comment] 2016-06-03 18:54
I currently get the following exception:

``"exceptionMessage": "Argument types do not match",
  "stackTrace": "   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMapExpression>b__5_0(ExpressionRequest tp)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
``

**Comment by jbogard** [comment] 2016-06-03 18:57
Ohhhhh ok. That's a bit different, that's from inside AutoMapper, instead of inside EF.

The exceptions inside AutoMapper are for runtime errors, not bugs. What you see there is a bug.

**Comment by michaelmsm89** [comment] 2016-06-03 18:58
I assumed this was because I am trying to map from one property to another that is of a different type? Is this not the case?

**Comment by jbogard** [comment] 2016-06-03 19:00
Does AssertConfigurationIsValid work for you?

**Comment by michaelmsm89** [comment] 2016-06-03 19:02
It passes AssertConfigurationIsValid. The exception isn't thrown until the projection is actually executed. The issue of course is that the exception doesn't give me a pointer to which particuar map or property causes the error, so it's hard to give you any sort of example POCO.

**Comment by jbogard** [comment] 2016-06-03 19:03
Right of course, it's just something buried in LINQ. Welp, let's reopen this then!

**Comment by TylerCarlson1** [comment] 2016-06-03 19:48
My Best guess would be from properties that are Nullable and that have a default that's not Nullable.  Or maybe a use value passing in an int but mapping to a property int?.  When you make expressions you have to account for the Nullable class yourself.

**Comment by TylerCarlson1** [comment] 2016-06-03 20:12
Looking into it more, and see the exception.  Do you have any inheritance on any of your classes?  Another thing could possibly be that if you have inheritance and your property map is going to Base Type and you are resolving an inherited type.  If that happened it might show this error as well, because I think both types have to be exactly the same, or so says the Condition Exception message.

Also this is getting called cause AllowNullDestinationValues is set to true.  If you can turn it off that might solve your problem, but it might cause other things to fail.

**Comment by jbogard** [comment] 2016-06-03 21:49
I'm also surprised viewing the detail doesn't show you anything but there
ya go.

**Comment by TylerCarlson1** [comment] 2016-06-03 23:08
All other attempts failed to replicate.  I found one way, which it to map using Struct and AllowNullDestinationValues=true.  Tries to make a constant null of a struct type and that throws this exception.  This is probably what it is.  See if you have any structs instead of classes in your dto objects.

**Comment by michaelmsm89** [comment] 2016-06-03 23:13
@TylerCarlson1 I don't have any structs, but I do have base classes. Still trying to figure out a small repro for the issue.

**Comment by TylerCarlson1** [comment] 2016-06-03 23:15
OK that's a COMPLETELY separate issue then, unless projection isn't meant to support structs.  I haven't seen any documentation on that.

**Comment by lbargaoanu** [comment] 2016-07-12 08:16
This can be closed until someone comes up with a repro,

**Comment by c-s-n** [comment] 2016-08-09 07:56
I'm running into the same (or at least similar) problem of an `ArgumentException` with "Argument types do not match" being thrown when using type conversions within projections. AutoMapper version is 5.0.2.

This is a stripped down use case of what shall be mapped. The conversion to enum is normally more advanced than shown in this example, and this is why there needs to be some conversion logic instead of a simple cast.

```C#
public enum MyTypes
{
    Val1, Val2
}

public class SourceModel
{
    public int EnumSourceProp { get; set; }
    public int EnumSameNameProp { get; set; }
    public double? NullableProp { get; set; }
    public int SameProp { get; set; }
}

public class DestModel
{
    public MyTypes EnumDestProp { get; set; }
    public MyTypes EnumSameNameProp { get; set; }
    public double NullableProp { get; set; }
    public int SameProp { get; set; }
}
```

The conversion cannot be implemented using a lambda expression within a `MapFrom`, as this will need to have a statement body, which however cannot be converted to an expression tree (and is not reusable). Like the documentation (of `MapFrom`) says, a custom value resolver applied via `ResolveUsing` is not supported when using LINQ query projections. This is why I went with a custom type converter:

```C#
public class MyTypesConverter : ITypeConverter<int, MyTypes>
{
    public MyTypes Convert(int source, MyTypes destination, ResolutionContext context)
    {
        return (MyTypes)source; // Normally more advanced
    }
}

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<int, MyTypes>()
            .ConvertUsing<MyTypesConverter>();
        CreateMap<SourceModel, DestModel>()
            .ForMember(dest => dest.EnumDestProp, opt => opt.MapFrom(src => src.EnumSourceProp))
            .ForMember(dest => dest.NullableProp, opt => opt.NullSubstitute(0));
    }
}
```

While a mapping of a collection using `DestModel[] result = mapper.Map<DestModel[]>(source);` works, the projection does not, resulting in an `ArgumentException`, very similar to the one [stated by michaelmsm89](https://github.com/AutoMapper/AutoMapper/issues/280#issuecomment-223663219)

```C#
[TestMethod]
public void ProjectionShouldWork()
{
    // Arrange
    IMapper mapper = new Mapper(new MapperConfiguration(cfg => cfg.AddProfile<MappingProfile>()));
    SourceModel[] source = new SourceModel[] { new SourceModel
    {
        EnumSourceProp = 1,
        NullableProp = null,
        SameProp = 3
    }};

    // Act
    IQueryable<DestModel> result = source.AsQueryable().ProjectTo<DestModel>(mapper.ConfigurationProvider);

    // Assert
    mapper.ConfigurationProvider.AssertConfigurationIsValid();
    Assert.IsInstanceOfType(result, typeof(IQueryable<DestModel>));
    Assert.AreEqual((MyTypes)source[0].EnumSourceProp, result.First().EnumDestProp);
    Assert.AreEqual((MyTypes)source[0].EnumSameNameProp, result.First().EnumSameNameProp);
    Assert.AreEqual(0, result.First().NullableProp);
    Assert.AreEqual(source[0].SameProp, result.First().SameProp);
}
```

So question: Is this a limitation or a bug? The only solution I see is to use `MapFrom` with a (static) helper method instead of the lambda, which however needs to be specified for every property, making the convention-based approach a bit useless:

```C#
.ForMember(dest => dest.EnumDestProp, opt => opt.MapFrom(src => myTypesConverter(src.EnumSourceProp)))
.ForMember(dest => dest.EnumSameNameProp, opt => opt.MapFrom(src => myTypesConverter(src.EnumSameNameProp)))
// ...
private static MyTypes myTypesConverter(int source)
{
    return (MyTypes)source; // Normally more advanced
}
```

**Comment by lbargaoanu** [comment] 2016-08-17 08:52
The limitation exists because what you specify as converter would be evaluated by the LINQ provider. Hopefully a simple expression would work, but not random converter code. About the exception messages, a PR is welcome.

**Comment by c-s-n** [comment] 2016-08-25 14:36
The recently released AutoMapper version 5.1.1 breaks projection with any type conversion in there (even simple ones), which used to work in 5.0.2! See e.g. [my above described projection use case](https://github.com/AutoMapper/AutoMapper/issues/280#issuecomment-238480634). This is clearly reproducible by up&downgrading the AutoMapper package.

Problem is again this `ArgumentException` with "Argument types do not match".

**Comment by lbargaoanu** [comment] 2016-08-25 14:48
Stack trace?

**Comment by c-s-n** [comment] 2016-08-25 16:35
After playing around with this a bit, I noticed that this new issue is not caused by the custom conversion, but by the `NullSubstitute` I used for the double property `NullableProp`. The literal `0` I supplied is apparently of type int and this is what makes it fail starting in version 5.1.1, i.e. there is no implicit conversion to double any more. Specifying `0.0` or `0d` works.
This is likely related to #1578 and #1579 where I will now add my findings (including stack trace).

What remains (and what could have helped here) is the mentioning of the failing property in the projection exception.

**Comment by Worthy7** [comment] 2016-08-31 05:17
+1 on properties mentioned in projection exceptions

**Comment by lbargaoanu** [comment] 2016-08-31 08:02
@Worthy7 PR?

**Comment by jigneshkvp** [comment] 2016-09-26 15:27
Hi,

I ran into similar issue with my code and got the same exception . The exception I see in the diagnostic tool in VS is:
	Exception: Exception thrown: 'System.InvalidOperationException' in mscorlib.dll ("Instances of abstract classes cannot be created."). Exception thrown: 'System.InvalidOperationException' in mscorlib.dll ("Instances of abstract classes cannot be created.")

My class setup is as follows:

public class ProductDto
{
  public List<AlternativeDto> Alternatives{get; set}
}

[KnownType(typeof(BusDto))]    
[KnownType(typeof(TruckDto))]
public abstract class AlternativeDto
{
   // other members like ID, Name, that are common to Bus and Truck
// Also there are more types defined apart from Truck and Bus in my actual code.

}

public class BusDto : AlternativeDto
{
 // its members
}

My mapping is:
CreateMap<Alternative, AlternativeDto>()
                .Include<Truck, TruckDto>()
                .Include<Bus, BusDto>();

I get an exception on this
var products =
                _productDataContext.Products.AsNoTracking()
                    .Where(product => product.SolutionId == solutionId)
                    .ProjectTo<ProductDto>()
                    .ToList();

I made this recent change to use ProjectTo for optimization, earlier was using more conventional way to retrieve products and then use _mappingEngine.Map<List<Product>, List<ProductDto>>()
(_mappingEngine = IMapper instance) to map all the object and its properties. 


Please advice.

**Comment by TylerCarlson1** [comment] 2016-09-26 15:58
@jigneshkvp  EF doesn't work for Automapper's Include.

Exception you get it because it's trying to make an instance of AlternativeDto which is abstract.  If you make it not abstract, then the mapping will work I think, but it will give you AlternativeDto every time.

**Comment by jigneshkvp** [comment] 2016-09-27 07:06
Hello @TylerCarlson1,

The same configuration/code (with the include)  works when I use **Mapper.Map<Product, ProductDto>()** and I get back proper results. As I mentioned, I am trying to use ProjectTo instead of .Map for optimization and that is when the same code fails.

**Comment by TylerCarlson1** [comment] 2016-09-27 13:13
And I told you why it would fail with ProjectTo vs Map.  It's just a limitation of what EF can do.  ProjectTo and Map do two VERY different things and have different limitations on what is and isn't achievable

I've run into the same issue and have been forced to use Map because of this.

**Comment by michaelmsm89** [comment] 2016-09-27 13:22
@jigneshkvp This isn't a similar issue and is a different exception message which is hopefully clear enough to explain the problem. Your issue shouldn't really be in this thread.

**Comment by jenseralmeida** [comment] 2016-10-16 14:46
Some additional details:

```C#
public class GenericPropertyBase<T>
    {
        public T Id { get; set; }
    }


    public class GenericProperty : GenericPropertyBase<int>
    {
        public string OtherProperty { get; set; }
    }

    public class GenericPropertyDto : GenericPropertyBase<int>
    {
        public string OtherProperty { get; set; }
    }

    public class GenericPropertyDtoProfile : Profile
    {
        public GenericPropertyDtoProfile()
        {
            CreateMap<GenericProperty, GenericPropertyDto>()
                //.ForMember(dst => dst.Id, opt => opt.MapFrom(src => (int)src.Id)) // this is not working also
                //.ForMember(dst => dst.Id, opt => opt.Ignore()) // now, it is working
                ;
        }
    }
```

And, at controller:

```C#
        [HttpGet]
        public IEnumerable<GenericPropertyDto> GetGeneric()
        {
            // uncomment the two lines below to create one entry on database
            // Context.GenericProperties.Add(new GenericProperty { OtherProperty = "Ok" });
            // Context.SaveChanges();
            return Context.GenericProperties.ProjectTo<GenericPropertyDto>().ToList();
        }
```

This results in exception detailed below


```
System.ArgumentException: Argument types do not match

   at System.Linq.Expressions.Expression.Constant(Object value, Type type)

   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)

   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)

   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)

   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)

   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, ConcurrentDictionary`2 typePairCount)

   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMapExpression>b__5_0(ExpressionRequest tp)

   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)

   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)

   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)

   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)

   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)

   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)

   at WebApplication.Controllers.Api.AccountsController.GetGeneric() in c:\dev\spot\financeneed\src\WebApp\Controllers\Api\AccountsController.cs:line 24

   at lambda_method(Closure , Object , Object[] )

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()```

**Comment by jenseralmeida** [comment] 2016-10-16 14:49
The only wait that I found to make this works is using the snippet below

```C#
            CreateMap<GenericProperty, GenericPropertyDto>()
                .ProjectUsing(src => new GenericPropertyDto { Id = src.Id, OtherProperty = src.OtherProperty });
```

**Comment by lbargaoanu** [comment] 2016-10-17 08:34
Try the MyGet build.

**Closed** 2016-11-17 21:32 UTC
